// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Frq struct {
	Term              *TermAtp   `json:"term"`
	AnswerWith        AnswerWith `json:"answerWith"`
	Correct           bool       `json:"correct"`
	UserMarkedCorrect *bool      `json:"userMarkedCorrect,omitempty"`
	AnsweredString    string     `json:"answeredString"`
}

type FRQInput struct {
	Term              *TermATPInput `json:"term"`
	AnswerWith        AnswerWith    `json:"answerWith"`
	Correct           bool          `json:"correct"`
	UserMarkedCorrect *bool         `json:"userMarkedCorrect,omitempty"`
	AnsweredString    string        `json:"answeredString"`
}

type FSRSCard struct {
	Difficulty    float64   `json:"difficulty"`
	Due           string    `json:"due"`
	Lapses        int32     `json:"lapses"`
	LastReview    *string   `json:"lastReview,omitempty"`
	LearningSteps int32     `json:"learningSteps"`
	Reps          int32     `json:"reps"`
	ScheduledDays int32     `json:"scheduledDays"`
	Stability     float64   `json:"stability"`
	State         FSRSState `json:"state"`
}

type FSRSCardInput struct {
	Difficulty    float64   `json:"difficulty"`
	Due           string    `json:"due"`
	Lapses        int32     `json:"lapses"`
	LastReview    *string   `json:"lastReview,omitempty"`
	LearningSteps int32     `json:"learningSteps"`
	Reps          int32     `json:"reps"`
	ScheduledDays int32     `json:"scheduledDays"`
	Stability     float64   `json:"stability"`
	State         FSRSState `json:"state"`
}

type FSRSReviewLog struct {
	ID            string     `json:"id"`
	Difficulty    float64    `json:"difficulty"`
	Due           string     `json:"due"`
	LearningSteps int32      `json:"learningSteps"`
	Rating        FSRSRating `json:"rating"`
	Review        string     `json:"review"`
	ScheduledDays int32      `json:"scheduledDays"`
	Stability     float64    `json:"stability"`
	State         FSRSState  `json:"state"`
}

type FSRSReviewLogInput struct {
	ID            string     `json:"id"`
	Difficulty    float64    `json:"difficulty"`
	Due           string     `json:"due"`
	LearningSteps int32      `json:"learningSteps"`
	Rating        FSRSRating `json:"rating"`
	Review        string     `json:"review"`
	ScheduledDays int32      `json:"scheduledDays"`
	Stability     float64    `json:"stability"`
	State         FSRSState  `json:"state"`
}

type FolderConnection struct {
	Edges    []*FolderEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type FolderEdge struct {
	Node   *Folder `json:"node"`
	Cursor string  `json:"cursor"`
}

type Mcq struct {
	Term               *TermAtp   `json:"term"`
	AnswerWith         AnswerWith `json:"answerWith"`
	Correct            bool       `json:"correct"`
	CorrectChoiceIndex int32      `json:"correctChoiceIndex"`
	AnsweredIndex      int32      `json:"answeredIndex"`
	Distractors        []*TermAtp `json:"distractors"`
}

type MCQInput struct {
	Term               *TermATPInput   `json:"term"`
	AnswerWith         AnswerWith      `json:"answerWith"`
	Correct            bool            `json:"correct"`
	CorrectChoiceIndex int32           `json:"correctChoiceIndex"`
	AnsweredIndex      int32           `json:"answeredIndex"`
	Distractors        []*TermATPInput `json:"distractors"`
}

type MatchActivity struct {
	DurationMs       int32      `json:"durationMs"`
	EndTimestamp     string     `json:"endTimestamp"`
	TermsIds         []string   `json:"termsIds"`
	IncorrectPairIds [][]string `json:"incorrectPairIds"`
}

type MatchActivityInput struct {
	DurationMs       int32      `json:"durationMs"`
	TermsIds         []string   `json:"termsIds"`
	IncorrectPairIds [][]string `json:"incorrectPairIds"`
}

type Mutation struct {
}

type NewTermInput struct {
	Term      *string `json:"term,omitempty"`
	Def       *string `json:"def,omitempty"`
	SortOrder int32   `json:"sortOrder"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PracticeTestInput struct {
	Timestamp *string          `json:"timestamp,omitempty"`
	Questions []*QuestionInput `json:"questions"`
}

type Query struct {
}

type Question struct {
	ID  string `json:"id"`
	Mcq *Mcq   `json:"mcq,omitempty"`
	Tfq *Tfq   `json:"tfq,omitempty"`
	Frq *Frq   `json:"frq,omitempty"`
}

type QuestionInput struct {
	Mcq *MCQInput `json:"mcq,omitempty"`
	Tfq *TFQInput `json:"tfq,omitempty"`
	Frq *FRQInput `json:"frq,omitempty"`
}

type StudysetConnection struct {
	Edges    []*StudysetEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type StudysetEdge struct {
	Node   *Studyset `json:"node"`
	Cursor string    `json:"cursor"`
}

type StudysetInput struct {
	Title     string  `json:"title"`
	Private   bool    `json:"private"`
	SubjectID *string `json:"subjectId,omitempty"`
}

type Tfq struct {
	Term         *TermAtp   `json:"term"`
	AnswerWith   AnswerWith `json:"answerWith"`
	Correct      bool       `json:"correct"`
	AnsweredBool bool       `json:"answeredBool"`
	Distractor   *TermAtp   `json:"distractor,omitempty"`
}

type TFQInput struct {
	Term         *TermATPInput `json:"term"`
	AnswerWith   AnswerWith    `json:"answerWith"`
	Correct      bool          `json:"correct"`
	AnsweredBool bool          `json:"answeredBool"`
	Distractor   *TermATPInput `json:"distractor,omitempty"`
}

type TermAtp struct {
	ID           string `json:"id"`
	TermSnapshot string `json:"termSnapshot"`
	DefSnapshot  string `json:"defSnapshot"`
}

type TermATPInput struct {
	ID           string `json:"id"`
	TermSnapshot string `json:"termSnapshot"`
	DefSnapshot  string `json:"defSnapshot"`
}

type TermConfusionPairInput struct {
	TermID                *string     `json:"termId,omitempty"`
	ConfusedTermID        *string     `json:"confusedTermId,omitempty"`
	AnsweredWith          *AnswerWith `json:"answeredWith,omitempty"`
	ConfusedCountIncrease *int32      `json:"confusedCountIncrease,omitempty"`
	ConfusedAt            *string     `json:"confusedAt,omitempty"`
}

type TermInput struct {
	ID        string  `json:"id"`
	Term      *string `json:"term,omitempty"`
	Def       *string `json:"def,omitempty"`
	SortOrder *int32  `json:"sortOrder,omitempty"`
}

type TermProgressInput struct {
	TermID                string  `json:"termId"`
	TermReviewedAt        *string `json:"termReviewedAt,omitempty"`
	DefReviewedAt         *string `json:"defReviewedAt,omitempty"`
	TermCorrectIncrease   *int32  `json:"termCorrectIncrease,omitempty"`
	TermIncorrectIncrease *int32  `json:"termIncorrectIncrease,omitempty"`
	DefCorrectIncrease    *int32  `json:"defCorrectIncrease,omitempty"`
	DefIncorrectIncrease  *int32  `json:"defIncorrectIncrease,omitempty"`
}

type AnswerWith string

const (
	AnswerWithTerm AnswerWith = "TERM"
	AnswerWithDef  AnswerWith = "DEF"
)

var AllAnswerWith = []AnswerWith{
	AnswerWithTerm,
	AnswerWithDef,
}

func (e AnswerWith) IsValid() bool {
	switch e {
	case AnswerWithTerm, AnswerWithDef:
		return true
	}
	return false
}

func (e AnswerWith) String() string {
	return string(e)
}

func (e *AnswerWith) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnswerWith(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnswerWith", str)
	}
	return nil
}

func (e AnswerWith) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnswerWith) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnswerWith) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AuthType string

const (
	AuthTypeUsernamePassword AuthType = "USERNAME_PASSWORD"
	AuthTypeOauthGoogle      AuthType = "OAUTH_GOOGLE"
)

var AllAuthType = []AuthType{
	AuthTypeUsernamePassword,
	AuthTypeOauthGoogle,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeUsernamePassword, AuthTypeOauthGoogle:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FSRSRating string

const (
	FSRSRatingManual FSRSRating = "MANUAL"
	FSRSRatingAgain  FSRSRating = "AGAIN"
	FSRSRatingHard   FSRSRating = "HARD"
	FSRSRatingGood   FSRSRating = "GOOD"
	FSRSRatingEasy   FSRSRating = "EASY"
)

var AllFSRSRating = []FSRSRating{
	FSRSRatingManual,
	FSRSRatingAgain,
	FSRSRatingHard,
	FSRSRatingGood,
	FSRSRatingEasy,
}

func (e FSRSRating) IsValid() bool {
	switch e {
	case FSRSRatingManual, FSRSRatingAgain, FSRSRatingHard, FSRSRatingGood, FSRSRatingEasy:
		return true
	}
	return false
}

func (e FSRSRating) String() string {
	return string(e)
}

func (e *FSRSRating) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FSRSRating(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FSRSRating", str)
	}
	return nil
}

func (e FSRSRating) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FSRSRating) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FSRSRating) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FSRSState string

const (
	FSRSStateNew        FSRSState = "NEW"
	FSRSStateLearning   FSRSState = "LEARNING"
	FSRSStateReview     FSRSState = "REVIEW"
	FSRSStateRelearning FSRSState = "RELEARNING"
)

var AllFSRSState = []FSRSState{
	FSRSStateNew,
	FSRSStateLearning,
	FSRSStateReview,
	FSRSStateRelearning,
}

func (e FSRSState) IsValid() bool {
	switch e {
	case FSRSStateNew, FSRSStateLearning, FSRSStateReview, FSRSStateRelearning:
		return true
	}
	return false
}

func (e FSRSState) String() string {
	return string(e)
}

func (e *FSRSState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FSRSState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FSRSState", str)
	}
	return nil
}

func (e FSRSState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FSRSState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FSRSState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubjectCategory string

const (
	SubjectCategoryLang          SubjectCategory = "LANG"
	SubjectCategoryStem          SubjectCategory = "STEM"
	SubjectCategorySocialStudies SubjectCategory = "SOCIAL_STUDIES"
	SubjectCategoryLa            SubjectCategory = "LA"
	SubjectCategoryMath          SubjectCategory = "MATH"
)

var AllSubjectCategory = []SubjectCategory{
	SubjectCategoryLang,
	SubjectCategoryStem,
	SubjectCategorySocialStudies,
	SubjectCategoryLa,
	SubjectCategoryMath,
}

func (e SubjectCategory) IsValid() bool {
	switch e {
	case SubjectCategoryLang, SubjectCategoryStem, SubjectCategorySocialStudies, SubjectCategoryLa, SubjectCategoryMath:
		return true
	}
	return false
}

func (e SubjectCategory) String() string {
	return string(e)
}

func (e *SubjectCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubjectCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubjectCategory", str)
	}
	return nil
}

func (e SubjectCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubjectCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubjectCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
