// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Frq struct {
	Term              *Term       `json:"term,omitempty"`
	AnswerWith        *AnswerWith `json:"answerWith,omitempty"`
	Correct           *bool       `json:"correct,omitempty"`
	UserMarkedCorrect *bool       `json:"userMarkedCorrect,omitempty"`
	AnsweredString    *string     `json:"answeredString,omitempty"`
}

type FRQInput struct {
	Term              *TermInput  `json:"term,omitempty"`
	AnswerWith        *AnswerWith `json:"answerWith,omitempty"`
	Correct           *bool       `json:"correct,omitempty"`
	UserMarkedCorrect *bool       `json:"userMarkedCorrect,omitempty"`
	AnsweredString    *string     `json:"answeredString,omitempty"`
}

type FSRSCard struct {
	Difficulty    float64   `json:"difficulty"`
	Due           string    `json:"due"`
	Lapses        int32     `json:"lapses"`
	LastReview    *string   `json:"lastReview,omitempty"`
	LearningSteps int32     `json:"learningSteps"`
	Reps          int32     `json:"reps"`
	ScheduledDays int32     `json:"scheduledDays"`
	Stability     float64   `json:"stability"`
	State         FSRSState `json:"state"`
}

type FSRSReviewLog struct {
	Difficulty    float64    `json:"difficulty"`
	Due           string     `json:"due"`
	LearningSteps int32      `json:"learningSteps"`
	Rating        FSRSRating `json:"rating"`
	Review        string     `json:"review"`
	ScheduledDays int32      `json:"scheduledDays"`
	Stability     float64    `json:"stability"`
	State         FSRSState  `json:"state"`
}

type FolderConnection struct {
	Edges    []*FolderEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type FolderEdge struct {
	Node   *Folder `json:"node"`
	Cursor string  `json:"cursor"`
}

type Mcq struct {
	Term               *Term       `json:"term,omitempty"`
	AnswerWith         *AnswerWith `json:"answerWith,omitempty"`
	Correct            *bool       `json:"correct,omitempty"`
	AnsweredTerm       *Term       `json:"answeredTerm,omitempty"`
	Distractors        []*Term     `json:"distractors,omitempty"`
	CorrectChoiceIndex *int32      `json:"correctChoiceIndex,omitempty"`
}

type MCQInput struct {
	Term               *TermInput   `json:"term,omitempty"`
	AnswerWith         *AnswerWith  `json:"answerWith,omitempty"`
	Correct            *bool        `json:"correct,omitempty"`
	AnsweredTerm       *TermInput   `json:"answeredTerm,omitempty"`
	Distractors        []*TermInput `json:"distractors,omitempty"`
	CorrectChoiceIndex *int32       `json:"correctChoiceIndex,omitempty"`
}

type MatchQuestion struct {
	Term         *Term       `json:"term,omitempty"`
	AnswerWith   *AnswerWith `json:"answerWith,omitempty"`
	Correct      *bool       `json:"correct,omitempty"`
	AnsweredTerm *Term       `json:"answeredTerm,omitempty"`
	Group        *int32      `json:"group,omitempty"`
}

type MatchQuestionInput struct {
	Term         *TermInput  `json:"term,omitempty"`
	AnswerWith   *AnswerWith `json:"answerWith,omitempty"`
	Correct      *bool       `json:"correct,omitempty"`
	AnsweredTerm *TermInput  `json:"answeredTerm,omitempty"`
	Group        *int32      `json:"group,omitempty"`
}

type Mutation struct {
}

type NewTermInput struct {
	Term      *string `json:"term,omitempty"`
	Def       *string `json:"def,omitempty"`
	SortOrder int32   `json:"sortOrder"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PracticeTestInput struct {
	ID               *string          `json:"id,omitempty"`
	Timestamp        *string          `json:"timestamp,omitempty"`
	StudysetID       *string          `json:"studysetId,omitempty"`
	QuestionsCorrect *int32           `json:"questionsCorrect,omitempty"`
	QuestionsTotal   *int32           `json:"questionsTotal,omitempty"`
	Questions        []*QuestionInput `json:"questions,omitempty"`
}

type Query struct {
}

type Question struct {
	QuestionType       *QuestionType      `json:"questionType,omitempty"`
	Mcq                *Mcq               `json:"mcq,omitempty"`
	TrueFalseQuestion  *TrueFalseQuestion `json:"trueFalseQuestion,omitempty"`
	MatchQuestionInput *MatchQuestion     `json:"matchQuestionInput,omitempty"`
	Frq                *Frq               `json:"frq,omitempty"`
}

type QuestionInput struct {
	QuestionType      *QuestionType           `json:"questionType,omitempty"`
	Mcq               *MCQInput               `json:"mcq,omitempty"`
	TrueFalseQuestion *TrueFalseQuestionInput `json:"trueFalseQuestion,omitempty"`
	MatchQuestion     *MatchQuestionInput     `json:"matchQuestion,omitempty"`
	Frq               *FRQInput               `json:"frq,omitempty"`
}

type StudysetConnection struct {
	Edges    []*StudysetEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type StudysetEdge struct {
	Node   *Studyset `json:"node"`
	Cursor string    `json:"cursor"`
}

type StudysetInput struct {
	Title     string  `json:"title"`
	Private   bool    `json:"private"`
	SubjectID *string `json:"subjectId,omitempty"`
}

type TermConfusionPairInput struct {
	TermID                *string     `json:"termId,omitempty"`
	ConfusedTermID        *string     `json:"confusedTermId,omitempty"`
	AnsweredWith          *AnswerWith `json:"answeredWith,omitempty"`
	ConfusedCountIncrease *int32      `json:"confusedCountIncrease,omitempty"`
	ConfusedAt            *string     `json:"confusedAt,omitempty"`
}

type TermInput struct {
	ID        string  `json:"id"`
	Term      *string `json:"term,omitempty"`
	Def       *string `json:"def,omitempty"`
	SortOrder *int32  `json:"sortOrder,omitempty"`
}

type TermProgressInput struct {
	TermID                string  `json:"termId"`
	TermReviewedAt        *string `json:"termReviewedAt,omitempty"`
	DefReviewedAt         *string `json:"defReviewedAt,omitempty"`
	TermLeitnerSystemBox  *int32  `json:"termLeitnerSystemBox,omitempty"`
	DefLeitnerSystemBox   *int32  `json:"defLeitnerSystemBox,omitempty"`
	TermCorrectIncrease   *int32  `json:"termCorrectIncrease,omitempty"`
	TermIncorrectIncrease *int32  `json:"termIncorrectIncrease,omitempty"`
	DefCorrectIncrease    *int32  `json:"defCorrectIncrease,omitempty"`
	DefIncorrectIncrease  *int32  `json:"defIncorrectIncrease,omitempty"`
}

type TrueFalseQuestion struct {
	Term         *Term       `json:"term,omitempty"`
	AnswerWith   *AnswerWith `json:"answerWith,omitempty"`
	Correct      *bool       `json:"correct,omitempty"`
	AnsweredBool *bool       `json:"answeredBool,omitempty"`
	Distractor   *Term       `json:"distractor,omitempty"`
}

type TrueFalseQuestionInput struct {
	Term         *TermInput  `json:"term,omitempty"`
	AnswerWith   *AnswerWith `json:"answerWith,omitempty"`
	Correct      *bool       `json:"correct,omitempty"`
	AnsweredBool *bool       `json:"answeredBool,omitempty"`
	Distractor   *TermInput  `json:"distractor,omitempty"`
}

type AnswerWith string

const (
	AnswerWithTerm AnswerWith = "TERM"
	AnswerWithDef  AnswerWith = "DEF"
)

var AllAnswerWith = []AnswerWith{
	AnswerWithTerm,
	AnswerWithDef,
}

func (e AnswerWith) IsValid() bool {
	switch e {
	case AnswerWithTerm, AnswerWithDef:
		return true
	}
	return false
}

func (e AnswerWith) String() string {
	return string(e)
}

func (e *AnswerWith) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnswerWith(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnswerWith", str)
	}
	return nil
}

func (e AnswerWith) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnswerWith) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnswerWith) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AuthType string

const (
	AuthTypeUsernamePassword AuthType = "USERNAME_PASSWORD"
	AuthTypeOauthGoogle      AuthType = "OAUTH_GOOGLE"
)

var AllAuthType = []AuthType{
	AuthTypeUsernamePassword,
	AuthTypeOauthGoogle,
}

func (e AuthType) IsValid() bool {
	switch e {
	case AuthTypeUsernamePassword, AuthTypeOauthGoogle:
		return true
	}
	return false
}

func (e AuthType) String() string {
	return string(e)
}

func (e *AuthType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthType", str)
	}
	return nil
}

func (e AuthType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FSRSRating string

const (
	FSRSRatingManual FSRSRating = "MANUAL"
	FSRSRatingAgain  FSRSRating = "AGAIN"
	FSRSRatingHard   FSRSRating = "HARD"
	FSRSRatingGood   FSRSRating = "GOOD"
	FSRSRatingEasy   FSRSRating = "EASY"
)

var AllFSRSRating = []FSRSRating{
	FSRSRatingManual,
	FSRSRatingAgain,
	FSRSRatingHard,
	FSRSRatingGood,
	FSRSRatingEasy,
}

func (e FSRSRating) IsValid() bool {
	switch e {
	case FSRSRatingManual, FSRSRatingAgain, FSRSRatingHard, FSRSRatingGood, FSRSRatingEasy:
		return true
	}
	return false
}

func (e FSRSRating) String() string {
	return string(e)
}

func (e *FSRSRating) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FSRSRating(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FSRSRating", str)
	}
	return nil
}

func (e FSRSRating) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FSRSRating) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FSRSRating) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FSRSState string

const (
	FSRSStateNew        FSRSState = "NEW"
	FSRSStateLearning   FSRSState = "LEARNING"
	FSRSStateReview     FSRSState = "REVIEW"
	FSRSStateRelearning FSRSState = "RELEARNING"
)

var AllFSRSState = []FSRSState{
	FSRSStateNew,
	FSRSStateLearning,
	FSRSStateReview,
	FSRSStateRelearning,
}

func (e FSRSState) IsValid() bool {
	switch e {
	case FSRSStateNew, FSRSStateLearning, FSRSStateReview, FSRSStateRelearning:
		return true
	}
	return false
}

func (e FSRSState) String() string {
	return string(e)
}

func (e *FSRSState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FSRSState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FSRSState", str)
	}
	return nil
}

func (e FSRSState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FSRSState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FSRSState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QuestionType string

const (
	QuestionTypeMcq       QuestionType = "MCQ"
	QuestionTypeTrueFalse QuestionType = "TRUE_FALSE"
	QuestionTypeMatch     QuestionType = "MATCH"
	QuestionTypeFrq       QuestionType = "FRQ"
)

var AllQuestionType = []QuestionType{
	QuestionTypeMcq,
	QuestionTypeTrueFalse,
	QuestionTypeMatch,
	QuestionTypeFrq,
}

func (e QuestionType) IsValid() bool {
	switch e {
	case QuestionTypeMcq, QuestionTypeTrueFalse, QuestionTypeMatch, QuestionTypeFrq:
		return true
	}
	return false
}

func (e QuestionType) String() string {
	return string(e)
}

func (e *QuestionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QuestionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QuestionType", str)
	}
	return nil
}

func (e QuestionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QuestionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QuestionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubjectCategory string

const (
	SubjectCategoryLang          SubjectCategory = "LANG"
	SubjectCategoryStem          SubjectCategory = "STEM"
	SubjectCategorySocialStudies SubjectCategory = "SOCIAL_STUDIES"
	SubjectCategoryLa            SubjectCategory = "LA"
	SubjectCategoryMath          SubjectCategory = "MATH"
)

var AllSubjectCategory = []SubjectCategory{
	SubjectCategoryLang,
	SubjectCategoryStem,
	SubjectCategorySocialStudies,
	SubjectCategoryLa,
	SubjectCategoryMath,
}

func (e SubjectCategory) IsValid() bool {
	switch e {
	case SubjectCategoryLang, SubjectCategoryStem, SubjectCategorySocialStudies, SubjectCategoryLa, SubjectCategoryMath:
		return true
	}
	return false
}

func (e SubjectCategory) String() string {
	return string(e)
}

func (e *SubjectCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubjectCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubjectCategory", str)
	}
	return nil
}

func (e SubjectCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubjectCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubjectCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
