insert into subject_keywords (subject_id, keyword) values
('lang-spanish',        'spanish'),
('lang-spanish',        'español'),
('lang-french',         'french'),
('lang-french',         'français'),
('lang-arabic',         'arabic'),
('lang-arabic',         'العربية'),
('lang-latin',          'latin'),
('lang-catalan',        'catalan'),
('lang-catalan',        'català'),
('lang-german',         'german'),
('lang-german',         'deutsch'),
('lang-russian',        'russian'),
('lang-russian',        'русский'),
('lang-chinese',        'chinese'),
('lang-chinese',        '中文'),
('lang-vietnamese',     'vietnamese'),
('lang-vietnamese',     'tiếng việt'),
('lang-lojban',         'lojban'),
('lang-dutch',          'dutch'),
('lang-italian',        'italian'),
('lang-korean',         'korean'),
('lang-indonesian',     'indonesian'),
('lang-english',        'english'),
('lang-portuguese',     'portuguese'),
('lang-welsh',          'welsh'),
('lang-japanese',       'japanese'),
('lang-polish',         'polish'),
('lang-hindi',          'hindi'),
('lang-thai',           'thai'),
('lang-bangla',         'bangla'),
('lang-bangla',         'বাংলা'),
('lang-hungarian',      'hungarian'),
('lang-turkish',        'turkish'),
('lang-swedish',        'swedish'),
('lang-finnish',        'finnish'),
('lang-czech',          'czech'),
('lang-danish',         'danish'),
('lang-greek',          'greek'),
('lang-esperanto',      'esperanto'),
('lang-irish',          'irish'),
('lang-haitian-creole', 'haitian creole'),
('lang-hawaiian',       'hawaiian'),
('lang-norwegian',      'norwegian'),
('lang-navajo',         'navajo'),
('lang-romanian',       'romanian'),
('lang-swahili',        'swahili'),
('lang-ukrainian',      'ukrainian'),
('lang-zulu',           'zulu'),
('biology',                'biology'),
('chemistry',              'chemistry'),
('chemistry',              'ap chem'),
('physics',                'physics'),
('health',                 'health'),
('forensic-science',       'forensic science'),
('environmental-science',  'environmental science'),
('nursing',                'nursing'),
('physical-science',       'physical science'),
('nutrition',              'nutrition'),
('medicine',               'medicine'),
('astronomy',              'astronomy'),
('neuroscience',           'neuroscience'),
('aviation',               'aviation'),
('chemical-engineering',   'chemical engineering'),
('civil-engineering',      'civil engineering'),
('architecture',           'architecture'),
('computer-science',       'computer science'),
('computer-science',       'java'),
('computer-science',       'javascript'),
('computer-science',       'python'),
('computer-science',       'C++'),
('computer-science',       'data structures'),
('computer-science',       'ap csa'),
('computer-science',       'ap csp'),
('biomedical-engineering', 'biomedical engineering'),
('aerospace-engineering',  'aerospace engineering'),
('electrical-engineering', 'electrical engineering'),
('earth-science',          'earth science'),
('history',         'history'),
('history',         'apush'),
('human-geography', 'human geography'),
('world-geography', 'world geography'),
('anthropology',    'anthropology'),
('sociology',       'sociology'),
('law',             'law'),
('psychology',      'psychology'),
('philosophy',      'philosophy'),
('microeconomics',  'microeconomics'),
('macroeconomics',  'macroeconomics'),
('finance',         'finance'),
('economics',       'economics'),
('business',        'business'),
('la-english',     'english'),
('la-lit',         'literature'),
('la-linguistics', 'linguistics'),
('geometry',      'geometry'),
('geometry',      'trigonometry'),
('algebra',       'algebra'),
('calc',          'calculus'),
('calc',          'ap calc'),
('precalc',       'pre-calculus'),
('arithmetic',    'arithmetic'),
('discrete-math', 'discrete math'),
('stat',          'statistics'),
('stat',          'ap stat');
