insert into subjects (name, category, keywords) values
('Spanish',    'LANG', 'español espanol espanyol'),
('French',     'LANG', 'français'),
('Arabic',     'LANG', 'العربية'),
('Latin',      'LANG', ''),
('Catalan',    'LANG', 'català'),
('German',     'LANG', 'deutsch'),
('Russian',    'LANG', 'русский'),
('Chinese',    'LANG', '中文 mandarin cantonese'),
('Vietnamese', 'LANG', 'tiếng việt tieng viet'),
('Lojban',     'LANG', ''),
('Dutch',      'LANG', ''),
('Italian',    'LANG', 'italiano'),
('Korean',     'LANG', ''),
('Indonesian', 'LANG', ''),
('English',    'LANG', ''),
('Spanish',    'LANG', ''),
('Portuguese', 'LANG', ''),
('Welsh',      'LANG', ''),
('Japanese',   'LANG', ''),
('Polish',     'LANG', ''),
('Hindi',      'LANG', ''),
('Thai',       'LANG', ''),
('Bangla',     'LANG', 'বাংলা bengali'),
('Hungarian',  'LANG', ''),
('Turkish',    'LANG', ''),
('Swedish',    'LANG', ''),
('Finnish',    'LANG', ''),
('Biology',                'STEM', 'bio'),
('Chemistry',              'STEM', 'chem'),
('Physics',                'STEM', ''),
('Health',                 'STEM', ''),
('Forensic Science',       'STEM', ''),
('Environmental Science',  'STEM', ''),
('Nursing',                'STEM', ''),
('Physical Science',       'STEM', ''),
('Nutrition',              'STEM', ''),
('Medicine',               'STEM', ''),
('Astronomy',              'STEM', ''),
('Neuroscience',           'STEM', ''),
('Aviation',               'STEM', ''),
('Chemical Engineering',   'STEM', ''),
('Civil Engineering',      'STEM', ''),
('Architecture',           'STEM', ''),
('Computer Science',       'STEM', 'compsci comp sci ap csp ap csa'),
('Biomedical Engineering', 'STEM', ''),
('Aerospace Engineering',  'STEM', ''),
('Electrical Engineering', 'STEM', ''),
('US History',             'SOCIAL_STUDIES', 'apush'),
('World History',          'SOCIAL_STUDIES', 'apwh'),
('Geography',              'SOCIAL_STUDIES', ''),
('Sociology',              'SOCIAL_STUDIES', ''),
('Law',                    'SOCIAL_STUDIES', ''),
('Psychology',             'SOCIAL_STUDIES', ''),
('Philosophy',             'SOCIAL_STUDIES', ''),
('Microeconomics',         'SOCIAL_STUDIES', ''),
('Macroeconomics',         'SOCIAL_STUDIES', ''),
('Finance',                'SOCIAL_STUDIES', ''),
('Economics',              'SOCIAL_STUDIES', ''),
('English',                          'LA', 'ela'),
('English Language & Composition',   'LA', 'ap lang'),
('English Literature & Composition', 'LA', 'ap lit'),
('Geometry',                         'MATH', 'trigonometry trig'),
('Algebra',                          'MATH', ''),
('Calculus',                         'MATH', 'calc'),
('Pre-Calculus',                     'MATH', 'precalc pre-calc'),
('Statistics',                       'MATH', 'precalc pre-calc stats ap stat');
