-- make sure you insert all subjects from subjects.sql first
insert into subject_keywords (subject_id, keyword) values
('spanish',        'spanish'),
('spanish',        'español'),
('french',         'french'),
('french',         'français'),
('arabic',         'arabic'),
('arabic',         'العربية'),
('latin',          'latin'),
('catalan',        'catalan'),
('catalan',        'català'),
('german',         'german'),
('german',         'deutsch'),
('russian',        'russian'),
('russian',        'русский'),
('chinese',        'chinese'),
('chinese',        '中文'),
('vietnamese',     'vietnamese'),
('vietnamese',     'tiếng việt'),
('lojban',         'lojban'),
('dutch',          'dutch'),
('italian',        'italian'),
('korean',         'korean'),
('indonesian',     'indonesian'),
('english',        'english'),
('portuguese',     'portuguese'),
('welsh',          'welsh'),
('japanese',       'japanese'),
('polish',         'polish'),
('hindi',          'hindi'),
('thai',           'thai'),
('bangla',         'bangla'),
('bangla',         'বাংলা'),
('hungarian',      'hungarian'),
('turkish',        'turkish'),
('swedish',        'swedish'),
('finnish',        'finnish'),
('czech',          'czech'),
('danish',         'danish'),
('greek',          'greek'),
('esperanto',      'esperanto'),
('irish',          'irish'),
('haitian-creole', 'haitian creole'),
('hawaiian',       'hawaiian'),
('norwegian',      'norwegian'),
('navajo',         'navajo'),
('romanian',       'romanian'),
('swahili',        'swahili'),
('ukrainian',      'ukrainian'),
('zulu',           'zulu'),
('biology',                'biology'),
('chemistry',              'chemistry'),
('chemistry',              'ap chem'),
('physics',                'physics'),
('health',                 'health'),
('forensic-science',       'forensic science'),
('environmental-science',  'environmental science'),
('nursing',                'nursing'),
('physical-science',       'physical science'),
('nutrition',              'nutrition'),
('medicine',               'medicine'),
('astronomy',              'astronomy'),
('neuroscience',           'neuroscience'),
('aviation',               'aviation'),
('chemical-engineering',   'chemical engineering'),
('civil-engineering',      'civil engineering'),
('architecture',           'architecture'),
('computer-science',       'computer science'),
('computer-science',       'java'),
('computer-science',       'javascript'),
('computer-science',       'python'),
('computer-science',       'C++'),
('computer-science',       'data structures'),
('computer-science',       'ap csa'),
('computer-science',       'ap csp'),
('biomedical-engineering', 'biomedical engineering'),
('aerospace-engineering',  'aerospace engineering'),
('electrical-engineering', 'electrical engineering'),
('earth-science',          'earth science'),
('history',         'history'),
('history',         'apush'),
('human-geography', 'human geography'),
('world-geography', 'world geography'),
('anthropology',    'anthropology'),
('sociology',       'sociology'),
('law',             'law'),
('psychology',      'psychology'),
('philosophy',      'philosophy'),
('microeconomics',  'microeconomics'),
('macroeconomics',  'macroeconomics'),
('finance',         'finance'),
('economics',       'economics'),
('business',        'business'),
('ela',         'english'),
('lit',         'literature'),
('linguistics', 'linguistics'),
('geometry',      'geometry'),
('geometry',      'trigonometry'),
('algebra',       'algebra'),
('calc',          'calculus'),
('calc',          'ap calc'),
('precalc',       'pre-calculus'),
('arithmetic',    'arithmetic'),
('discrete-math', 'discrete math'),
('stat',          'statistics'),
('stat',          'ap stat');
