insert into subjects (id, name, category) values
('lang-spanish',        'Spanish',         'LANG'),
('lang-french',         'French',          'LANG'),
('lang-arabic',         'Arabic',          'LANG'),
('lang-latin',          'Latin',           'LANG'),
('lang-catalan',        'Catalan',         'LANG'),
('lang-german',         'German',          'LANG'),
('lang-russian',        'Russian',         'LANG'),
('lang-chinese',        'Chinese',         'LANG'),
('lang-vietnamese',     'Vietnamese',      'LANG'),
('lang-lojban',         'Lojban',          'LANG'),
('lang-dutch',          'Dutch',           'LANG'),
('lang-italian',        'Italian',         'LANG'),
('lang-korean',         'Korean',          'LANG'),
('lang-indonesian',     'Indonesian',      'LANG'),
('lang-english',        'English',         'LANG'),
('lang-portuguese',     'Portuguese',      'LANG'),
('lang-welsh',          'Welsh',           'LANG'),
('lang-japanese',       'Japanese',        'LANG'),
('lang-polish',         'Polish',          'LANG'),
('lang-hindi',          'Hindi',           'LANG'),
('lang-thai',           'Thai',            'LANG'),
('lang-bangla',         'Bangla',          'LANG'),
('lang-hungarian',      'Hungarian',       'LANG'),
('lang-turkish',        'Turkish',         'LANG'),
('lang-swedish',        'Swedish',         'LANG'),
('lang-finnish',        'Finnish',         'LANG'),
('lang-czech',          'Czech',           'LANG'),
('lang-danish',         'Danish',          'LANG'),
('lang-greek',          'Greek',           'LANG'),
('lang-esperanto',      'Esperanto',       'LANG'),
('lang-irish',          'Irish',           'LANG'),
('lang-haitian-creole', 'Haitian Creole',  'LANG'),
('lang-hawaiian',       'Hawaiian',        'LANG'),
('lang-norwegian',      'Norwegian',       'LANG'),
('lang-navajo',         'Navajo',          'LANG'),
('lang-romanian',       'Romanian',        'LANG'),
('lang-swahili',        'Swahili',         'LANG'),
('lang-ukrainian',      'Ukrainian',       'LANG'),
('lang-zulu',           'Zulu',            'LANG'),
('biology',                'Biology',                'STEM'),
('chemistry',              'Chemistry',              'STEM'),
('physics',                'Physics',                'STEM'),
('health',                 'Health',                 'STEM'),
('forensic-science',       'Forensic Science',       'STEM'),
('environmental-science',  'Environmental Science',  'STEM'),
('nursing',                'Nursing',                'STEM'),
('physical-science',       'Physical Science',       'STEM'),
('nutrition',              'Nutrition',              'STEM'),
('medicine',               'Medicine',               'STEM'),
('astronomy',              'Astronomy',              'STEM'),
('neuroscience',           'Neuroscience',           'STEM'),
('aviation',               'Aviation',               'STEM'),
('chemical-engineering',   'Chemical Engineering',   'STEM'),
('civil-engineering',      'Civil Engineering',      'STEM'),
('architecture',           'Architecture',           'STEM'),
('computer-science',       'Computer Science',       'STEM'),
('biomedical-engineering', 'Biomedical Engineering', 'STEM'),
('aerospace-engineering',  'Aerospace Engineering',  'STEM'),
('electrical-engineering', 'Electrical Engineering', 'STEM'),
('earth-science',          'Earth Science',          'STEM'),
('history',         'History',         'SOCIAL_STUDIES'),
('human-geography', 'Human Geography', 'SOCIAL_STUDIES'),
('world-geography', 'World Geography', 'SOCIAL_STUDIES'),
('anthropology',    'Anthropology',    'SOCIAL_STUDIES'),
('sociology',       'Sociology',       'SOCIAL_STUDIES'),
('law',             'Law',             'SOCIAL_STUDIES'),
('psychology',      'Psychology',      'SOCIAL_STUDIES'),
('philosophy',      'Philosophy',      'SOCIAL_STUDIES'),
('microeconomics',  'Microeconomics',  'SOCIAL_STUDIES'),
('macroeconomics',  'Macroeconomics',  'SOCIAL_STUDIES'),
('finance',         'Finance',         'SOCIAL_STUDIES'),
('economics',       'Economics',       'SOCIAL_STUDIES'),
('business',        'Business',        'SOCIAL_STUDIES'),
('la-english',     'English',     'LA'),
('la-lit',         'Literature',  'LA'),
('la-linguistics', 'Linguistics', 'LA'),
('geometry',      'Geometry',      'MATH'),
('algebra',       'Algebra',       'MATH'),
('calc',          'Calculus',      'MATH'),
('precalc',       'Pre-Calculus',  'MATH'),
('arithmetic',    'Arithmetic',    'MATH'),
('discrete-math', 'Discrete Math', 'MATH'),
('stat',          'Statistics',    'MATH');
