insert into subjects (id, name, category) values
('spanish',        'Spanish',         'LANG'),
('french',         'French',          'LANG'),
('arabic',         'Arabic',          'LANG'),
('latin',          'Latin',           'LANG'),
('catalan',        'Catalan',         'LANG'),
('german',         'German',          'LANG'),
('russian',        'Russian',         'LANG'),
('chinese',        'Chinese',         'LANG'),
('vietnamese',     'Vietnamese',      'LANG'),
('lojban',         'Lojban',          'LANG'),
('dutch',          'Dutch',           'LANG'),
('italian',        'Italian',         'LANG'),
('korean',         'Korean',          'LANG'),
('indonesian',     'Indonesian',      'LANG'),
('english',        'English',         'LANG'),
('portuguese',     'Portuguese',      'LANG'),
('welsh',          'Welsh',           'LANG'),
('japanese',       'Japanese',        'LANG'),
('polish',         'Polish',          'LANG'),
('hindi',          'Hindi',           'LANG'),
('thai',           'Thai',            'LANG'),
('bangla',         'Bangla',          'LANG'),
('hungarian',      'Hungarian',       'LANG'),
('turkish',        'Turkish',         'LANG'),
('swedish',        'Swedish',         'LANG'),
('finnish',        'Finnish',         'LANG'),
('czech',          'Czech',           'LANG'),
('danish',         'Danish',          'LANG'),
('greek',          'Greek',           'LANG'),
('esperanto',      'Esperanto',       'LANG'),
('irish',          'Irish',           'LANG'),
('haitian-creole', 'Haitian Creole',  'LANG'),
('hawaiian',       'Hawaiian',        'LANG'),
('norwegian',      'Norwegian',       'LANG'),
('navajo',         'Navajo',          'LANG'),
('romanian',       'Romanian',        'LANG'),
('swahili',        'Swahili',         'LANG'),
('ukrainian',      'Ukrainian',       'LANG'),
('zulu',           'Zulu',            'LANG'),
('biology',                'Biology',                'STEM'),
('chemistry',              'Chemistry',              'STEM'),
('physics',                'Physics',                'STEM'),
('health',                 'Health',                 'STEM'),
('forensic-science',       'Forensic Science',       'STEM'),
('environmental-science',  'Environmental Science',  'STEM'),
('nursing',                'Nursing',                'STEM'),
('physical-science',       'Physical Science',       'STEM'),
('nutrition',              'Nutrition',              'STEM'),
('medicine',               'Medicine',               'STEM'),
('astronomy',              'Astronomy',              'STEM'),
('neuroscience',           'Neuroscience',           'STEM'),
('aviation',               'Aviation',               'STEM'),
('chemical-engineering',   'Chemical Engineering',   'STEM'),
('civil-engineering',      'Civil Engineering',      'STEM'),
('architecture',           'Architecture',           'STEM'),
('computer-science',       'Computer Science',       'STEM'),
('biomedical-engineering', 'Biomedical Engineering', 'STEM'),
('aerospace-engineering',  'Aerospace Engineering',  'STEM'),
('electrical-engineering', 'Electrical Engineering', 'STEM'),
('earth-science',          'Earth Science',          'STEM'),
('history',         'History',         'SOCIAL_STUDIES'),
('human-geography', 'Human Geography', 'SOCIAL_STUDIES'),
('world-geography', 'World Geography', 'SOCIAL_STUDIES'),
('anthropology',    'Anthropology',    'SOCIAL_STUDIES'),
('sociology',       'Sociology',       'SOCIAL_STUDIES'),
('law',             'Law',             'SOCIAL_STUDIES'),
('psychology',      'Psychology',      'SOCIAL_STUDIES'),
('philosophy',      'Philosophy',      'SOCIAL_STUDIES'),
('microeconomics',  'Microeconomics',  'SOCIAL_STUDIES'),
('macroeconomics',  'Macroeconomics',  'SOCIAL_STUDIES'),
('finance',         'Finance',         'SOCIAL_STUDIES'),
('economics',       'Economics',       'SOCIAL_STUDIES'),
('business',        'Business',        'SOCIAL_STUDIES'),
('ela',         'English',     'LA'),
('lit',         'Literature',  'LA'),
('linguistics', 'Linguistics', 'LA'),
('geometry',      'Geometry',      'MATH'),
('algebra',       'Algebra',       'MATH'),
('calc',          'Calculus',      'MATH'),
('precalc',       'Pre-Calculus',  'MATH'),
('arithmetic',    'Arithmetic',    'MATH'),
('discrete-math', 'Discrete Math', 'MATH'),
('stat',          'Statistics',    'MATH');
