package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"fmt"
	"quizfreely/api/auth"
	"quizfreely/api/graph"
	"quizfreely/api/graph/model"
	"strings"

	"github.com/georgysavva/scany/v2/pgxscan"
	"github.com/rs/zerolog/log"
	pgx "github.com/jackc/pgx/v5"
)

// CreateStudyset is the resolver for the createStudyset field.
func (r *mutationResolver) CreateStudyset(ctx context.Context, studyset model.StudysetInput, draft bool, folderID *string) (*model.Studyset, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	title := "Untitled Studyset"
	if len(studyset.Title) > 0 && len(studyset.Title) < 200 && validTitleRegex.MatchString(studyset.Title) {
		title = studyset.Title
	} else if draft && len(studyset.Title) == 0 {
		title = ""
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	sql := `
		INSERT INTO public.studysets (user_id, title, private, subject_id, draft)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, user_id, title, private, subject_id, draft, seo_indexing_approved,
			to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
	`
	var newStudyset model.Studyset
	err = pgxscan.Get(ctx, tx, &newStudyset, sql, authedUser.ID, title, studyset.Private, studyset.SubjectID, draft)
	if err != nil {
		return nil, fmt.Errorf("failed to create studyset: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	if folderID != nil {
		r.SetStudysetFolder(ctx, *newStudyset.ID, *folderID)
	}

	return &newStudyset, nil
}

// UpdateStudyset is the resolver for the updateStudyset field.
func (r *mutationResolver) UpdateStudyset(ctx context.Context, id string, studyset *model.StudysetInput, draft bool) (*model.Studyset, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if studyset == nil {
		return r.Query().Studyset(ctx, id)
	}

	// if the user doesn't own the studyset, the query affects 0 rows, and we return a "not found" error
	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var updatedStudyset model.Studyset
	title := "Untitled Studyset"
	if len(studyset.Title) > 0 && len(studyset.Title) < 200 && validTitleRegex.MatchString(studyset.Title) {
		title = studyset.Title
	} else if draft && len(studyset.Title) == 0 {
		title = ""
	}

	sql := `
		UPDATE public.studysets
		SET title = $1, private = $2, subject_id = $3, draft = $4, updated_at = now()
		WHERE id = $5 AND (user_id = $6 OR COALESCE($7, false) = true)
		RETURNING id, user_id, title, private, subject_id, draft, seo_indexing_approved,
			to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
	`
	err = pgxscan.Get(ctx, tx, &updatedStudyset, sql, title, studyset.Private, studyset.SubjectID, draft, id, authedUser.ID, authedUser.ModPerms)
	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, fmt.Errorf("studyset not found")
		}
		return nil, fmt.Errorf("failed to update studyset: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &updatedStudyset, nil
}

// CreateTerms is the resolver for the createTerms field.
func (r *mutationResolver) CreateTerms(ctx context.Context, studysetID string, terms []*model.NewTermInput) ([]*model.Term, error) {
	if len(terms) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many terms in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Check ownership
	var exists bool
	err = tx.QueryRow(ctx, "SELECT exists(SELECT 1 FROM studysets WHERE id = $1 AND user_id = $2)", studysetID, authedUser.ID).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset ownership: %w", err)
	}
	if !exists {
		return nil, fmt.Errorf("studyset not found or not owned by user")
	}

	if len(terms) == 0 {
		return []*model.Term{}, nil
	}

	values := make([]interface{}, 0, len(terms)*4)
	placeholders := make([]string, 0, len(terms))

	values = append(values, r.UsercontentBaseURL)
	for i, t := range terms {
		placeholders = append(placeholders, fmt.Sprintf("($%d,$%d,$%d,$%d)", i*4+2, i*4+3, i*4+4, i*4+5))
		values = append(values, studysetID, t.Term, t.Def, t.SortOrder)
	}

	sql := fmt.Sprintf(`
		INSERT INTO terms (studyset_id, term, def, sort_order)
		VALUES %s
		RETURNING id, term, def, ($1||term_image_key) as term_image_url, ($1||def_image_key) as def_image_url, sort_order,
			to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
	`, strings.Join(placeholders, ","))

	var newTerms []*model.Term
	err = pgxscan.Select(ctx, tx, &newTerms, sql, values...)
	if err != nil {
		return nil, fmt.Errorf("failed to insert terms: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return newTerms, nil
}

// UpdateTerms is the resolver for the updateTerms field.
func (r *mutationResolver) UpdateTerms(ctx context.Context, studysetID string, terms []*model.TermInput) ([]*model.Term, error) {
	if len(terms) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many terms in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Check ownership
	var exists bool
	err = tx.QueryRow(ctx, "SELECT exists(SELECT 1 FROM studysets WHERE id = $1 AND user_id = $2)", studysetID, authedUser.ID).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset ownership: %w", err)
	}
	if !exists {
		return nil, fmt.Errorf("studyset not found or not owned by user")
	}

	if len(terms) == 0 {
		return []*model.Term{}, nil
	}

	values := make([]interface{}, 0, len(terms)*4)
	placeholders := make([]string, 0, len(terms))

	for i, t := range terms {
		placeholders = append(placeholders, fmt.Sprintf(
			"($%d::uuid, $%d::text, $%d::text, $%d::int)",
			i*4+3, i*4+4, i*4+5, i*4+6,
		))
		values = append(values, t.ID, t.Term, t.Def, t.SortOrder)
	}

	sql := fmt.Sprintf(
		`UPDATE terms AS t
		SET term = v.term, def = v.def, sort_order = v.sort_order, updated_at = now()
		FROM (VALUES
			%s
		) AS v(id, term, def, sort_order)
		WHERE t.id = v.id AND t.studyset_id = $1
		RETURNING t.id, t.term, t.def, ($2||t.term_image_key) as term_image_url, ($2||t.def_image_key) as def_image_url, t.sort_order,
			to_char(t.created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(t.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at`,
		strings.Join(placeholders, ","),
	)

	var updatedTerms []*model.Term
	err = pgxscan.Select(
		ctx,
		tx,
		&updatedTerms,
		sql,
		append(
			[]interface{}{studysetID, r.UsercontentBaseURL},
			values...,
		)...,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update terms: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return updatedTerms, nil
}

// DeleteTerms is the resolver for the deleteTerms field.
func (r *mutationResolver) DeleteTerms(ctx context.Context, studysetID string, ids []string) ([]string, error) {
	if len(ids) == 0 {
		return []string{}, nil
	} else if len(ids) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many items in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Check ownership
	var exists bool
	err = tx.QueryRow(ctx, "SELECT exists(SELECT 1 FROM studysets WHERE id = $1 AND user_id = $2)", studysetID, authedUser.ID).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset ownership: %w", err)
	}
	if !exists {
		return nil, fmt.Errorf("studyset not found or not owned by user")
	}

	var deletedIDs []string
	sql := "DELETE FROM terms WHERE id = ANY($1) AND studyset_id = $2 RETURNING id"
	err = pgxscan.Select(ctx, tx, &deletedIDs, sql, ids, studysetID)
	if err != nil {
		return nil, fmt.Errorf("failed to delete terms: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return deletedIDs, nil
}

// DeleteStudyset is the resolver for the deleteStudyset field.
func (r *mutationResolver) DeleteStudyset(ctx context.Context, id string) (*string, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	var deletedID string
	err := pgxscan.Get(
		ctx,
		r.DB,
		&deletedID,
		"DELETE FROM public.studysets WHERE id = $1 AND user_id = $2 RETURNING id",
		id,
		authedUser.ID,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("studyset not found")
		}
		return nil, fmt.Errorf("failed to delete studyset: %w", err)
	}

	return &deletedID, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, displayName *string) (*model.AuthedUser, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if displayName != nil {
		trimmedDisplayName := strings.TrimSpace(*displayName)
		if len(trimmedDisplayName) < 1 || len(trimmedDisplayName) > 32 {
			return nil, fmt.Errorf("display name must be between 1 and 32 characters")
		}
		if *displayName != trimmedDisplayName {
			return nil, fmt.Errorf("display name must not have leading or trailing whitespace")
		}
	} else {
		return authedUser, nil
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var updatedUser model.AuthedUser
	err = pgxscan.Get(ctx, tx, &updatedUser,
		`UPDATE auth.users SET display_name = $1 WHERE id = $2 RETURNING id, username, display_name`,
		*displayName, authedUser.ID)

	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &updatedUser, nil
}

// UpdateTermProgress is the resolver for the updateTermProgress field.
func (r *mutationResolver) UpdateTermProgress(ctx context.Context, termProgress []*model.TermProgressInput) ([]*model.TermProgress, error) {
	if len(termProgress) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many items in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if len(termProgress) == 0 {
		return []*model.TermProgress{}, nil
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// ---- Build bulk insert ----
	valueStrings := make([]string, 0, len(termProgress))
	valueArgs := make([]interface{}, 0, len(termProgress)*10)
	termIDs := make([]string, len(termProgress))

	for i, p := range termProgress {
		termIDs[i] = p.TermID
		// Each row has 10 parameters (adjust if needed)
		base := i*10 + 1
		valueStrings = append(valueStrings, fmt.Sprintf(
			"($%d::uuid,$%d::uuid,$%d::timestamptz,$%d::timestamptz,CASE WHEN $%d IS NOT NULL THEN 1 ELSE 0 END,$%d::timestamptz,$%d::timestamptz,CASE WHEN $%d IS NOT NULL THEN 1 ELSE 0 END,$%d::int,$%d::int,COALESCE($%d::int,0),COALESCE($%d::int,0),COALESCE($%d::int,0),COALESCE($%d::int,0))",
			base, base+1, base+2, base+2, base+2, base+3, base+3, base+3, base+4, base+5, base+6, base+7, base+8, base+9,
		))

		valueArgs = append(valueArgs,
			p.TermID,
			authedUser.ID,
			p.TermReviewedAt,
			p.DefReviewedAt,
			p.TermLeitnerSystemBox,
			p.DefLeitnerSystemBox,
			p.TermCorrectIncrease,
			p.TermIncorrectIncrease,
			p.DefCorrectIncrease,
			p.DefIncorrectIncrease,
		)
	}

	query := fmt.Sprintf(`
		INSERT INTO term_progress (
			term_id, user_id,
			term_first_reviewed_at, term_last_reviewed_at,
			term_review_count,
			def_first_reviewed_at, def_last_reviewed_at,
			def_review_count,
			term_leitner_system_box, def_leitner_system_box,
			term_correct_count, term_incorrect_count,
			def_correct_count, def_incorrect_count
		)
		SELECT v.term_id::uuid, v.user_id::uuid,
			v.term_first_reviewed_at::timestamptz, v.term_last_reviewed_at::timestamptz,
			v.term_review_count::int,
			v.def_first_reviewed_at::timestamptz, v.def_last_reviewed_at::timestamptz,
			v.def_review_count::int,
			v.term_leitner_system_box::int, v.def_leitner_system_box::int,
			v.term_correct_count::int, v.term_incorrect_count::int,
			v.def_correct_count::int, v.def_incorrect_count::int
		FROM (VALUES %s) AS v(
			term_id, user_id,
			term_first_reviewed_at, term_last_reviewed_at,
			term_review_count,
			def_first_reviewed_at, def_last_reviewed_at,
			def_review_count,
			term_leitner_system_box, def_leitner_system_box,
			term_correct_count, term_incorrect_count,
			def_correct_count, def_incorrect_count
		)
		JOIN terms t ON t.id = v.term_id::uuid
		JOIN studysets s ON s.id = t.studyset_id
		WHERE s.draft = false AND (s.private = false OR s.user_id = v.user_id::uuid)
		ON CONFLICT (term_id, user_id) DO UPDATE SET
			term_last_reviewed_at = COALESCE(EXCLUDED.term_last_reviewed_at, term_progress.term_last_reviewed_at),
			def_last_reviewed_at = COALESCE(EXCLUDED.def_last_reviewed_at, term_progress.def_last_reviewed_at),
			term_leitner_system_box = EXCLUDED.term_leitner_system_box,
			def_leitner_system_box = EXCLUDED.def_leitner_system_box,
			term_review_count = term_progress.term_review_count +
				(CASE WHEN EXCLUDED.term_last_reviewed_at IS NOT NULL THEN 1 ELSE 0 END),
			def_review_count = term_progress.def_review_count +
				(CASE WHEN EXCLUDED.def_last_reviewed_at IS NOT NULL THEN 1 ELSE 0 END),
			term_correct_count = term_progress.term_correct_count + EXCLUDED.term_correct_count,
			term_incorrect_count = term_progress.term_incorrect_count + EXCLUDED.term_incorrect_count,
			def_correct_count = term_progress.def_correct_count + EXCLUDED.def_correct_count,
			def_incorrect_count = term_progress.def_incorrect_count + EXCLUDED.def_incorrect_count
		RETURNING term_progress.id,
			to_char(term_progress.term_first_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as term_first_reviewed_at,
			to_char(term_progress.term_last_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as term_last_reviewed_at,
			term_progress.term_review_count,
			to_char(term_progress.def_first_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as def_first_reviewed_at,
			to_char(term_progress.def_last_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as def_last_reviewed_at,
			term_progress.def_review_count,
			term_progress.term_leitner_system_box, term_progress.def_leitner_system_box,
			term_progress.term_correct_count, term_progress.term_incorrect_count,
			term_progress.def_correct_count, term_progress.def_incorrect_count
	`, strings.Join(valueStrings, ","))

	var results []*model.TermProgress
	if err := pgxscan.Select(ctx, tx, &results, query, valueArgs...); err != nil {
		return nil, fmt.Errorf("bulk upsert failed: %w", err)
	}

	if len(results) != len(termProgress) {
		return nil, fmt.Errorf("some terms not found or not accessible")
	}

	// ---- Bulk insert into history ----
	if len(results) > 0 {
		histVals := make([]string, 0, len(results))
		histArgs := make([]interface{}, 0, len(results)*6)
		for i, tp := range results {
			base := i*6 + 1
			histVals = append(histVals, fmt.Sprintf("($%d,$%d,$%d,$%d,$%d,$%d)", base, base+1, base+2, base+3, base+4, base+5))
			histArgs = append(histArgs,
				authedUser.ID,
				termIDs[i],
				tp.TermCorrectCount,
				tp.TermIncorrectCount,
				tp.DefCorrectCount,
				tp.DefIncorrectCount,
			)
		}
		histQuery := fmt.Sprintf(`
			INSERT INTO term_progress_history (
				user_id, term_id, term_correct_count, term_incorrect_count,
				def_correct_count, def_incorrect_count
			) VALUES %s`, strings.Join(histVals, ","))

		if _, err := tx.Exec(ctx, histQuery, histArgs...); err != nil {
			return nil, fmt.Errorf("failed to insert into term_progress_history: %w", err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return results, nil
}

// RecordConfusedTerms is the resolver for the recordConfusedTerms field.
func (r *mutationResolver) RecordConfusedTerms(ctx context.Context, confusedTerms []*model.TermConfusionPairInput) (*bool, error) {
	var success bool
	if len(confusedTerms) > MaxBatchMutationSize {
		success = false
		return &success, fmt.Errorf("too many items in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		success = false
		return &success, fmt.Errorf("not authenticated")
	}

	if len(confusedTerms) == 0 {
		success = false
		return &success, nil
	}

	values := make([]interface{}, 0, len(confusedTerms)*5)
	values = append(
		values,
		*authedUser.ID,
	)
	placeholders := make([]string, 0, len(confusedTerms))

	sameTermAndConfusedTerm := false
	for i, ct := range confusedTerms {
		if *ct.TermID == *ct.ConfusedTermID {
			sameTermAndConfusedTerm = true
			continue
		}
		placeholders = append(
			placeholders,
			fmt.Sprintf(
				"($1,$%d,$%d,$%d,$%d,$%d)",
				i*5+2, i*5+3, i*5+4, i*5+5, i*5+6,
			),
		)
		values = append(
			values,
			ct.TermID,
			ct.ConfusedTermID,
			ct.AnsweredWith,
			ct.ConfusedCountIncrease,
			ct.ConfusedAt,
		)
	}

	sql := fmt.Sprintf(`INSERT INTO term_confusion_pairs (
	user_id, term_id, confused_term_id, answered_with, confused_count, last_confused_at
)
SELECT v.user_id, v.term_id, v.confused_term_id, v.answered_with, v.confused_count, v.last_confused_at
FROM (VALUES %s) AS v(user_id, term_id, confused_term_id, answered_with, confused_count, last_confused_at)
JOIN terms t1 ON t1.id = v.term_id::uuid
JOIN studysets s1 ON s1.id = t1.studyset_id
JOIN terms t2 ON t2.id = v.confused_term_id::uuid
JOIN studysets s2 ON s2.id = t2.studyset_id
WHERE (s1.draft = false AND (s1.private = false OR s1.user_id = v.user_id::uuid))
  AND (s2.draft = false AND (s2.private = false OR s2.user_id = v.user_id::uuid))
ON CONFLICT (user_id, term_id, confused_term_id, answered_with)
DO UPDATE SET confused_count = term_confusion_pairs.confused_count + EXCLUDED.confused_count,
	last_confused_at = EXCLUDED.last_confused_at`,
		strings.Join(placeholders, ","),
	)
	_, err := r.DB.Exec(ctx, sql, values...)
	if err != nil {
		success = false
		return &success, fmt.Errorf("failed to insert/update confusion pairs: %w", err)
	}

	success = true
	if sameTermAndConfusedTerm {
		return &success, errors.New("Confusion pairs with same term and confused term were not inserted")
	}
	return &success, nil
}

// RecordPracticeTest is the resolver for the recordPracticeTest field.
func (r *mutationResolver) RecordPracticeTest(ctx context.Context, input *model.PracticeTestInput) (*model.PracticeTest, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	var practiceTest model.PracticeTest
	err := pgxscan.Get(
		ctx,
		r.DB,
		&practiceTest,
		`INSERT INTO practice_tests
	(timestamp, user_id, studyset_id, questions_correct, questions_total, questions)
SELECT now(), $1, s.id, $3, $4, $5
FROM studysets s
WHERE s.id = $2 AND s.draft = false AND (s.private = false OR s.user_id = $1)
RETURNING
	id,
	studyset_id,
	to_char(timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as timestamp,
	questions_correct,
	questions_total,
	questions`,
		authedUser.ID,
		input.StudysetID,
		input.QuestionsCorrect,
		input.QuestionsTotal,
		input.Questions,
	)
	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, fmt.Errorf("studyset not found or not accessible")
		}
		return nil, fmt.Errorf("database error in RecordPracticeTest: %w", err)
	}

	return &practiceTest, nil
}

// UpdatePracticeTest is the resolver for the updatePracticeTest field.
func (r *mutationResolver) UpdatePracticeTest(ctx context.Context, input *model.PracticeTestInput) (*model.PracticeTest, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if input.ID == nil {
		return nil, fmt.Errorf("practice test id cannot be null when updating")
	}

	var practiceTest model.PracticeTest
	err := pgxscan.Get(
		ctx,
		r.DB,
		&practiceTest,
		`UPDATE practice_tests SET questions_correct = $3, questions_total = $4, questions = $5
WHERE user_id = $1 AND id = $2
RETURNING
	id,
	studyset_id,
	to_char(timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as timestamp,
	questions_correct,
	questions_total,
	questions`,
		authedUser.ID,
		input.ID,
		input.QuestionsCorrect,
		input.QuestionsTotal,
		input.Questions,
	)
	if err != nil {
		return nil, fmt.Errorf("database error in updatePracticeTest: %w", err)
	}

	return &practiceTest, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string) (*model.Folder, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if len(name) > MaxFolderNameLen {
		name = name[:MaxFolderNameLen]
	}

	sql := `
		INSERT INTO folders (user_id, name)
		VALUES ($1, $2)
		RETURNING id, name
	`
	var newFolder model.Folder
	err := pgxscan.Get(ctx, r.DB, &newFolder, sql, authedUser.ID, name)
	if err != nil {
		return nil, fmt.Errorf("failed to create studyset: %w", err)
	}

	return &newFolder, nil
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, id string, name string) (*model.Folder, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if len(name) > MaxFolderNameLen {
		name = name[:MaxFolderNameLen]
	}

	sql := `
		UPDATE folders SET name = $1
		WHERE user_id = $2 AND id = $3
		RETURNING id, name
	`
	var folder model.Folder
	err := pgxscan.Get(ctx, r.DB, &folder, sql, name, authedUser.ID, id)
	if err != nil {
		return nil, fmt.Errorf("failed to rename folder: %w", err)
	}

	return &folder, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id string) (*string, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	res, err := r.DB.Exec(
		ctx,
		"DELETE FROM folders WHERE id = $1 AND user_id = $2",
		id,
		authedUser.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete folder: %w", err)
	}

	if res.RowsAffected() == 0 {
		return nil, fmt.Errorf("folder not found or access denied")
	}

	return &id, nil
}

// SetStudysetFolder is the resolver for the setStudysetFolder field.
func (r *mutationResolver) SetStudysetFolder(ctx context.Context, studysetID string, folderID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	_, err := r.DB.Exec(
		ctx,
		`INSERT INTO folder_studysets (user_id, studyset_id, folder_id)
		SELECT $1, s.id, f.id
		FROM studysets s
		JOIN folders f ON f.id = $3::uuid
		WHERE s.id = $2::uuid
		  AND ((s.draft = false AND s.private = false) OR s.user_id = $1)
		  AND f.user_id = $1
		ON CONFLICT (user_id, studyset_id) DO UPDATE
		SET folder_id = EXCLUDED.folder_id`,
		authedUser.ID,
		studysetID,
		folderID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to add/move studyset to folder: %w", err)
	}

	yay := true
	return &yay, nil
}

// RemoveStudysetFromFolder is the resolver for the removeStudysetFromFolder field.
func (r *mutationResolver) RemoveStudysetFromFolder(ctx context.Context, studysetID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	_, err := r.DB.Exec(
		ctx,
		"DELETE FROM folder_studysets WHERE studyset_id = $1 AND user_id = $2",
		studysetID,
		authedUser.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to unsave studyset: %w", err)
	}

	yay := true
	return &yay, nil
}

// SaveStudyset is the resolver for the saveStudyset field.
func (r *mutationResolver) SaveStudyset(ctx context.Context, studysetID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	res, err := r.DB.Exec(
		ctx,
		`INSERT INTO saved_studysets (user_id, studyset_id)
		SELECT $1, id FROM studysets
		WHERE id = $2 AND (private = false OR user_id = $1) AND draft = false`,
		authedUser.ID,
		studysetID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to save studyset: %w", err)
	}
	if res.RowsAffected() == 0 {
		return nil, fmt.Errorf("studyset not found, private, or is a draft")
	}

	yay := true
	return &yay, nil
}

// UnsaveStudyset is the resolver for the unsaveStudyset field.
func (r *mutationResolver) UnsaveStudyset(ctx context.Context, studysetID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	_, err := r.DB.Exec(
		ctx,
		"DELETE FROM saved_studysets WHERE studyset_id = $1 AND user_id = $2",
		studysetID,
		authedUser.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to unsave studyset: %w", err)
	}

	yay := true
	return &yay, nil
}

// SetStudysetSeoIndexing is the resolver for the setStudysetSeoIndexing field.
func (r *mutationResolver) SetStudysetSeoIndexing(ctx context.Context, studysetID string, approved bool) (bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return false, errors.New("not authenticated")
	}
	if authedUser.ModPerms == nil || !*authedUser.ModPerms {
		return false, errors.New("missing moderator permissions needed to set studyset SEO indexing approval")
	}
	tag, err := r.DB.Exec(
		ctx,
		"UPDATE studysets SET seo_indexing_approved = $1 WHERE id = $2",
		approved,
		studysetID,
	)
	if err != nil {
		log.Error().Err(err).Msg("DB Error in SetStudysetSeoIndexing")
		return false, errors.New("DB Error in SetStudysetSeoIndexing")
	}
    return tag.RowsAffected() == 1, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
