package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"quizfreely/api/auth"
	"quizfreely/api/graph"
	"quizfreely/api/graph/model"
	"strings"
	"time"

	"github.com/georgysavva/scany/v2/pgxscan"
	pgx "github.com/jackc/pgx/v5"
	"github.com/rs/zerolog/log"
)

// CreateStudyset is the resolver for the createStudyset field.
func (r *mutationResolver) CreateStudyset(ctx context.Context, studyset model.StudysetInput, draft bool, folderID *string) (*model.Studyset, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	title := "Untitled Studyset"
	if len(studyset.Title) > 0 && len(studyset.Title) < 200 && validTitleRegex.MatchString(studyset.Title) {
		title = studyset.Title
	} else if draft && len(studyset.Title) == 0 {
		title = ""
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	sql := `
		INSERT INTO public.studysets (user_id, title, private, subject_id, draft)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, user_id, title, private, subject_id, draft, seo_indexing_approved,
			to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
	`
	var newStudyset model.Studyset
	err = pgxscan.Get(ctx, tx, &newStudyset, sql, authedUser.ID, title, studyset.Private, studyset.SubjectID, draft)
	if err != nil {
		return nil, fmt.Errorf("failed to create studyset: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	if folderID != nil {
		r.SetStudysetFolder(ctx, *newStudyset.ID, *folderID)
	}

	return &newStudyset, nil
}

// UpdateStudyset is the resolver for the updateStudyset field.
func (r *mutationResolver) UpdateStudyset(ctx context.Context, id string, studyset *model.StudysetInput, draft bool) (*model.Studyset, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if studyset == nil {
		return r.Query().Studyset(ctx, id)
	}

	// if the user doesn't own the studyset, the query affects 0 rows, and we return a "not found" error
	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var updatedStudyset model.Studyset
	title := "Untitled Studyset"
	if len(studyset.Title) > 0 && len(studyset.Title) < 200 && validTitleRegex.MatchString(studyset.Title) {
		title = studyset.Title
	} else if draft && len(studyset.Title) == 0 {
		title = ""
	}

	sql := `
		UPDATE public.studysets
		SET title = $1, private = $2, subject_id = $3, draft = $4, updated_at = now()
		WHERE id = $5 AND (user_id = $6 OR COALESCE($7, false) = true)
		RETURNING id, user_id, title, private, subject_id, draft, seo_indexing_approved,
			to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
	`
	err = pgxscan.Get(ctx, tx, &updatedStudyset, sql, title, studyset.Private, studyset.SubjectID, draft, id, authedUser.ID, authedUser.ModPerms)
	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, fmt.Errorf("studyset not found")
		}
		return nil, fmt.Errorf("failed to update studyset: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &updatedStudyset, nil
}

// CreateTerms is the resolver for the createTerms field.
func (r *mutationResolver) CreateTerms(ctx context.Context, studysetID string, terms []*model.NewTermInput) ([]*model.Term, error) {
	if len(terms) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many terms in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Check ownership
	var exists bool
	err = tx.QueryRow(ctx, "SELECT exists(SELECT 1 FROM studysets WHERE id = $1 AND user_id = $2)", studysetID, authedUser.ID).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset ownership: %w", err)
	}
	if !exists {
		return nil, fmt.Errorf("studyset not found or not owned by user")
	}

	if len(terms) == 0 {
		return []*model.Term{}, nil
	}

	values := make([]interface{}, 0, len(terms)*4)
	placeholders := make([]string, 0, len(terms))

	values = append(values, r.UsercontentBaseURL)
	for i, t := range terms {
		placeholders = append(placeholders, fmt.Sprintf("($%d,$%d,$%d,$%d)", i*4+2, i*4+3, i*4+4, i*4+5))
		values = append(values, studysetID, t.Term, t.Def, t.SortOrder)
	}

	sql := fmt.Sprintf(`
		INSERT INTO terms (studyset_id, term, def, sort_order)
		VALUES %s
		RETURNING id, term, def, ($1||term_image_key) as term_image_url, ($1||def_image_key) as def_image_url, sort_order,
			to_char(created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
	`, strings.Join(placeholders, ","))

	var newTerms []*model.Term
	err = pgxscan.Select(ctx, tx, &newTerms, sql, values...)
	if err != nil {
		return nil, fmt.Errorf("failed to insert terms: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return newTerms, nil
}

// UpdateTerms is the resolver for the updateTerms field.
func (r *mutationResolver) UpdateTerms(ctx context.Context, studysetID string, terms []*model.TermInput) ([]*model.Term, error) {
	if len(terms) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many terms in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Check ownership
	var exists bool
	err = tx.QueryRow(ctx, "SELECT exists(SELECT 1 FROM studysets WHERE id = $1 AND user_id = $2)", studysetID, authedUser.ID).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset ownership: %w", err)
	}
	if !exists {
		return nil, fmt.Errorf("studyset not found or not owned by user")
	}

	if len(terms) == 0 {
		return []*model.Term{}, nil
	}

	values := make([]interface{}, 0, len(terms)*4)
	placeholders := make([]string, 0, len(terms))

	for i, t := range terms {
		placeholders = append(placeholders, fmt.Sprintf(
			"($%d::uuid, $%d::text, $%d::text, $%d::int)",
			i*4+3, i*4+4, i*4+5, i*4+6,
		))
		values = append(values, t.ID, t.Term, t.Def, t.SortOrder)
	}

	sql := fmt.Sprintf(
		`UPDATE terms AS t
		SET term = v.term, def = v.def, sort_order = v.sort_order, updated_at = now()
		FROM (VALUES
			%s
		) AS v(id, term, def, sort_order)
		WHERE t.id = v.id AND t.studyset_id = $1
		RETURNING t.id, t.term, t.def, ($2||t.term_image_key) as term_image_url, ($2||t.def_image_key) as def_image_url, t.sort_order,
			to_char(t.created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
			to_char(t.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at`,
		strings.Join(placeholders, ","),
	)

	var updatedTerms []*model.Term
	err = pgxscan.Select(
		ctx,
		tx,
		&updatedTerms,
		sql,
		append(
			[]interface{}{studysetID, r.UsercontentBaseURL},
			values...,
		)...,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update terms: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return updatedTerms, nil
}

// DeleteTerms is the resolver for the deleteTerms field.
func (r *mutationResolver) DeleteTerms(ctx context.Context, studysetID string, ids []string) ([]string, error) {
	if len(ids) == 0 {
		return []string{}, nil
	} else if len(ids) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many items in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// Check ownership
	var exists bool
	err = tx.QueryRow(ctx, "SELECT exists(SELECT 1 FROM studysets WHERE id = $1 AND user_id = $2)", studysetID, authedUser.ID).Scan(&exists)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset ownership: %w", err)
	}
	if !exists {
		return nil, fmt.Errorf("studyset not found or not owned by user")
	}

	var deletedIDs []string
	sql := "DELETE FROM terms WHERE id = ANY($1) AND studyset_id = $2 RETURNING id"
	err = pgxscan.Select(ctx, tx, &deletedIDs, sql, ids, studysetID)
	if err != nil {
		return nil, fmt.Errorf("failed to delete terms: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return deletedIDs, nil
}

// DeleteStudyset is the resolver for the deleteStudyset field.
func (r *mutationResolver) DeleteStudyset(ctx context.Context, id string) (*string, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	var deletedID string
	err := pgxscan.Get(
		ctx,
		r.DB,
		&deletedID,
		"DELETE FROM public.studysets WHERE id = $1 AND user_id = $2 RETURNING id",
		id,
		authedUser.ID,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("studyset not found")
		}
		return nil, fmt.Errorf("failed to delete studyset: %w", err)
	}

	return &deletedID, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, displayName *string) (*model.AuthedUser, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if displayName != nil {
		trimmedDisplayName := strings.TrimSpace(*displayName)
		if len(trimmedDisplayName) < 1 || len(trimmedDisplayName) > 32 {
			return nil, fmt.Errorf("display name must be between 1 and 32 characters")
		}
		if *displayName != trimmedDisplayName {
			return nil, fmt.Errorf("display name must not have leading or trailing whitespace")
		}
	} else {
		return authedUser, nil
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var updatedUser model.AuthedUser
	err = pgxscan.Get(ctx, tx, &updatedUser,
		`UPDATE auth.users SET display_name = $1 WHERE id = $2 RETURNING id, username, display_name`,
		*displayName, authedUser.ID)

	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &updatedUser, nil
}

// UpdateTermProgress is the resolver for the updateTermProgress field.
func (r *mutationResolver) UpdateTermProgress(ctx context.Context, termProgress []*model.TermProgressInput) ([]*model.TermProgress, error) {
	if len(termProgress) > MaxBatchMutationSize {
		return nil, fmt.Errorf("too many items in a single request (max %d)", MaxBatchMutationSize)
	}

	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if len(termProgress) == 0 {
		return []*model.TermProgress{}, nil
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	// ---- Build bulk insert ----
	valueStrings := make([]string, 0, len(termProgress))
	valueArgs := make([]interface{}, 0, len(termProgress)*8)
	termIDs := make([]string, len(termProgress))

	for i, p := range termProgress {
		termIDs[i] = p.TermID
		// Each row has 8 parameters
		base := i*8 + 1
		valueStrings = append(valueStrings, fmt.Sprintf(
			"($%d::uuid,$%d::uuid,$%d::timestamptz,$%d::timestamptz,CASE WHEN $%d IS NOT NULL THEN 1 ELSE 0 END,$%d::timestamptz,$%d::timestamptz,CASE WHEN $%d IS NOT NULL THEN 1 ELSE 0 END,COALESCE($%d::int,0),COALESCE($%d::int,0),COALESCE($%d::int,0),COALESCE($%d::int,0))",
			base, base+1, base+2, base+2, base+2, base+3, base+3, base+3, base+4, base+5, base+6, base+7,
		))

		valueArgs = append(valueArgs,
			p.TermID,
			authedUser.ID,
			p.TermReviewedAt,
			p.DefReviewedAt,
			p.TermCorrectIncrease,
			p.TermIncorrectIncrease,
			p.DefCorrectIncrease,
			p.DefIncorrectIncrease,
		)
	}

	query := fmt.Sprintf(`
		INSERT INTO term_progress (
			term_id, user_id,
			term_first_reviewed_at, term_last_reviewed_at,
			term_review_count,
			def_first_reviewed_at, def_last_reviewed_at,
			def_review_count,
			term_correct_count, term_incorrect_count,
			def_correct_count, def_incorrect_count
		)
		SELECT v.term_id::uuid, v.user_id::uuid,
			v.term_first_reviewed_at::timestamptz, v.term_last_reviewed_at::timestamptz,
			v.term_review_count::int,
			v.def_first_reviewed_at::timestamptz, v.def_last_reviewed_at::timestamptz,
			v.def_review_count::int,
			v.term_correct_count::int, v.term_incorrect_count::int,
			v.def_correct_count::int, v.def_incorrect_count::int
		FROM (VALUES %s) AS v(
			term_id, user_id,
			term_first_reviewed_at, term_last_reviewed_at,
			term_review_count,
			def_first_reviewed_at, def_last_reviewed_at,
			def_review_count,
			term_correct_count, term_incorrect_count,
			def_correct_count, def_incorrect_count
		)
		JOIN terms t ON t.id = v.term_id::uuid
		JOIN studysets s ON s.id = t.studyset_id
		WHERE s.draft = false AND (s.private = false OR s.user_id = v.user_id::uuid)
		ON CONFLICT (term_id, user_id) DO UPDATE SET
			term_last_reviewed_at = COALESCE(EXCLUDED.term_last_reviewed_at, term_progress.term_last_reviewed_at),
			def_last_reviewed_at = COALESCE(EXCLUDED.def_last_reviewed_at, term_progress.def_last_reviewed_at),
			term_review_count = term_progress.term_review_count +
				(CASE WHEN EXCLUDED.term_last_reviewed_at IS NOT NULL THEN 1 ELSE 0 END),
			def_review_count = term_progress.def_review_count +
				(CASE WHEN EXCLUDED.def_last_reviewed_at IS NOT NULL THEN 1 ELSE 0 END),
			term_correct_count = term_progress.term_correct_count + EXCLUDED.term_correct_count,
			term_incorrect_count = term_progress.term_incorrect_count + EXCLUDED.term_incorrect_count,
			def_correct_count = term_progress.def_correct_count + EXCLUDED.def_correct_count,
			def_incorrect_count = term_progress.def_incorrect_count + EXCLUDED.def_incorrect_count
		RETURNING term_progress.id,
			to_char(term_progress.term_first_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as term_first_reviewed_at,
			to_char(term_progress.term_last_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as term_last_reviewed_at,
			term_progress.term_review_count,
			to_char(term_progress.def_first_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as def_first_reviewed_at,
			to_char(term_progress.def_last_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as def_last_reviewed_at,
			term_progress.def_review_count,
			term_progress.term_correct_count, term_incorrect_count,
			term_progress.def_correct_count, term_progress.def_incorrect_count
	`, strings.Join(valueStrings, ","))

	var results []*model.TermProgress
	if err := pgxscan.Select(ctx, tx, &results, query, valueArgs...); err != nil {
		return nil, fmt.Errorf("bulk upsert failed: %w", err)
	}

	if len(results) != len(termProgress) {
		return nil, fmt.Errorf("some terms not found or not accessible")
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return results, nil
}

// RecordPracticeTest is the resolver for the recordPracticeTest field.
func (r *mutationResolver) RecordPracticeTest(ctx context.Context, input model.PracticeTestInput) (*model.PracticeTest, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var questionsCorrect int32 = 0
	var questionsTotal int32 = int32(len(input.Questions))

	nowStr := time.Now().Format(time.RFC3339)
	termProgressMap := make(map[string]*model.TermProgressInput)

	var questionRows []model.QuestionRow
	var allTermIDs []string

	for i, q := range input.Questions {
		if q == nil {
			continue
		}
		var termID string
		var termStr, defStr string
		var qType string
		var answerWith model.AnswerWith
		correct := false
		var data interface{}

		if q.Mcq != nil && q.Mcq.Term != nil {
			termID = q.Mcq.Term.ID
			termStr = q.Mcq.Term.Term
			defStr = q.Mcq.Term.Def
			qType = "MCQ"
			answerWith = q.Mcq.AnswerWith
			correct = q.Mcq.Correct
			data = map[string]interface{}{
				"distractors":        q.Mcq.Distractors,
				"correctChoiceIndex": q.Mcq.CorrectChoiceIndex,
				"answeredIndex":      q.Mcq.AnsweredIndex,
			}
			allTermIDs = append(allTermIDs, termID)
			for _, d := range q.Mcq.Distractors {
				if d != nil {
					allTermIDs = append(allTermIDs, d.ID)
				}
			}
		} else if q.Tfq != nil && q.Tfq.Term != nil {
			termID = q.Tfq.Term.ID
			termStr = q.Tfq.Term.Term
			defStr = q.Tfq.Term.Def
			qType = "TFQ"
			answerWith = q.Tfq.AnswerWith
			correct = q.Tfq.Correct
			data = map[string]interface{}{
				"answeredBool": q.Tfq.AnsweredBool,
				"distractor":   q.Tfq.Distractor,
			}
			allTermIDs = append(allTermIDs, termID)
			if q.Tfq.Distractor != nil {
				allTermIDs = append(allTermIDs, q.Tfq.Distractor.ID)
			}
		} else if q.Frq != nil && q.Frq.Term != nil {
			termID = q.Frq.Term.ID
			termStr = q.Frq.Term.Term
			defStr = q.Frq.Term.Def
			qType = "FRQ"
			answerWith = q.Frq.AnswerWith
			correct = q.Frq.Correct
			userMarkedCorrect := false
			if q.Frq.UserMarkedCorrect != nil && *q.Frq.UserMarkedCorrect {
				correct = true
				userMarkedCorrect = true
			}
			data = map[string]interface{}{
				"answeredString":    q.Frq.AnsweredString,
				"userMarkedCorrect": userMarkedCorrect,
			}
			allTermIDs = append(allTermIDs, termID)
		}

		if correct {
			questionsCorrect++
		}

		dataBytes, err := json.Marshal(data)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal question data: %w", err)
		}

		var tid *string
		if termID != "" {
			tid = &termID
		}
		questionRows = append(questionRows, model.QuestionRow{
			TermID:     tid,
			Term:       termStr,
			Def:        defStr,
			Type:       qType,
			AnswerWith: answerWith,
			Correct:    correct,
			Position:   int32(i),
			Data:       dataBytes,
		})

		if termID == "" {
			continue
		}

		tp, exists := termProgressMap[termID]
		if !exists {
			tp = &model.TermProgressInput{
				TermID: termID,
			}
			termProgressMap[termID] = tp
		}

		var termCorrectIncrease int32
		var termIncorrectIncrease int32
		var defCorrectIncrease int32
		var defIncorrectIncrease int32

		if correct {
			if answerWith == model.AnswerWithDef {
				defCorrectIncrease = 1
				tp.DefReviewedAt = &nowStr
			} else {
				termCorrectIncrease = 1
				tp.TermReviewedAt = &nowStr
			}
		} else {
			if answerWith == model.AnswerWithDef {
				defIncorrectIncrease = 1
				tp.DefReviewedAt = &nowStr
			} else {
				termIncorrectIncrease = 1
				tp.TermReviewedAt = &nowStr
			}
		}

		if tp.TermCorrectIncrease == nil {
			tp.TermCorrectIncrease = &termCorrectIncrease
		} else {
			*tp.TermCorrectIncrease += termCorrectIncrease
		}
		if tp.TermIncorrectIncrease == nil {
			tp.TermIncorrectIncrease = &termIncorrectIncrease
		} else {
			*tp.TermIncorrectIncrease += termIncorrectIncrease
		}
		if tp.DefCorrectIncrease == nil {
			tp.DefCorrectIncrease = &defCorrectIncrease
		} else {
			*tp.DefCorrectIncrease += defCorrectIncrease
		}
		if tp.DefIncorrectIncrease == nil {
			tp.DefIncorrectIncrease = &defIncorrectIncrease
		} else {
			*tp.DefIncorrectIncrease += defIncorrectIncrease
		}
	}

	var studysetIDs []string
	if len(allTermIDs) > 0 {
		var studysets []struct {
			ID      string `db:"id"`
			Private bool   `db:"private"`
			UserID  string `db:"user_id"`
			Draft   bool   `db:"draft"`
		}
		err = pgxscan.Select(ctx, tx, &studysets, `
			SELECT id, private, user_id, draft
			FROM studysets
			WHERE id IN (SELECT DISTINCT studyset_id FROM terms WHERE id = ANY($1))
		`, allTermIDs)
		if err != nil {
			return nil, fmt.Errorf("database error checking studysets: %w", err)
		}

		for _, s := range studysets {
			if s.Draft || (s.Private && (authedUser.ID == nil || s.UserID != *authedUser.ID)) {
				return nil, fmt.Errorf("studyset not found or not accessible")
			}
			studysetIDs = append(studysetIDs, s.ID)
		}
	}

	var practiceTest model.PracticeTest
	err = pgxscan.Get(
		ctx,
		tx,
		&practiceTest,
		`INSERT INTO practice_tests
	(timestamp, user_id, questions_correct, questions_total)
VALUES (now(), $1, $2, $3)
RETURNING
	id,
	to_char(timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as timestamp,
	questions_correct,
	questions_total`,
		authedUser.ID,
		questionsCorrect,
		questionsTotal,
	)
	if err != nil {
		return nil, fmt.Errorf("database error in RecordPracticeTest: %w", err)
	}

	if len(questionRows) > 0 {
		placeholders := make([]string, len(questionRows))
		args := make([]interface{}, 0, len(questionRows)*8+1)
		args = append(args, practiceTest.ID)
		for i, qr := range questionRows {
			base := i*8 + 2
			placeholders[i] = fmt.Sprintf("($1, $%d, $%d, $%d, $%d, $%d, $%d, $%d, $%d)", base, base+1, base+2, base+3, base+4, base+5, base+6, base+7)
			args = append(args, qr.TermID, qr.Term, qr.Def, qr.Type, qr.AnswerWith, qr.Correct, qr.Position, qr.Data)
		}
		sql := fmt.Sprintf("INSERT INTO practice_test_questions (practice_test_id, term_id, term_snapshot, def_snapshot, type, answer_with, correct, position, data) VALUES %s RETURNING id, term_id, type, answer_with, correct", strings.Join(placeholders, ","))

		var insertedQuestions []struct {
			ID         string           `db:"id"`
			TermID     *string          `db:"term_id"`
			Type       string           `db:"type"`
			AnswerWith model.AnswerWith `db:"answer_with"`
			Correct    bool             `db:"correct"`
		}

		err = pgxscan.Select(ctx, tx, &insertedQuestions, sql, args...)
		if err != nil {
			return nil, fmt.Errorf("failed to insert practice test questions: %w", err)
		}

		reviewEventPlaceholders := make([]string, len(insertedQuestions))
		reviewEventArgs := make([]interface{}, 0, len(insertedQuestions)*9+1)
		reviewEventArgs = append(reviewEventArgs, authedUser.ID)

		for i, iq := range insertedQuestions {
			base := i*8 + 2
			reviewEventPlaceholders[i] = fmt.Sprintf("($1, $%d, $%d, $%d, $%d, $%d, $%d, $%d, $%d)",
				base, base+1, base+2, base+3, base+4, base+5, base+6, base+7)

			var answeredTermID *string
			var answeredString *string
			qInput := input.Questions[i]

			if qInput.Mcq != nil {
				mcq := qInput.Mcq
				choicesCount := len(mcq.Distractors) + 1
				choices := make([]*model.TermATPInput, choicesCount)
				correctIdx := mcq.CorrectChoiceIndex
				for j := 0; j < choicesCount; j++ {
					if int32(j) == correctIdx {
						choices[j] = mcq.Term
					} else if int32(j) < correctIdx {
						choices[j] = mcq.Distractors[j]
					} else {
						choices[j] = mcq.Distractors[j-1]
					}
				}
				if mcq.AnsweredIndex >= 0 && mcq.AnsweredIndex < int32(len(choices)) {
					answeredTermID = &choices[mcq.AnsweredIndex].ID
				}
			} else if qInput.Tfq != nil {
				tfq := qInput.Tfq
				if tfq.Correct {
					answeredTermID = &tfq.Term.ID
				} else {
					if tfq.AnsweredBool {
						if tfq.Distractor != nil {
							answeredTermID = &tfq.Distractor.ID
						}
					}
				}
			} else if qInput.Frq != nil {
				answeredString = &qInput.Frq.AnsweredString
			}

			reviewEventArgs = append(reviewEventArgs,
				iq.TermID,
				iq.ID,
				iq.Correct,
				iq.AnswerWith,
				answeredTermID,
				iq.Type,
				model.ReviewActivityTypePracticeTest,
				answeredString,
			)
		}

		reSql := fmt.Sprintf(`INSERT INTO review_events (
			user_id, term_id, practice_test_question_id, correct, answer_with,
			answered_term_id, practice_test_question_type, review_activity_type,
			answered_string
		) VALUES %s`, strings.Join(reviewEventPlaceholders, ","))

		if _, err := tx.Exec(ctx, reSql, reviewEventArgs...); err != nil {
			return nil, fmt.Errorf("failed to insert review events: %w", err)
		}

		practiceTest.Questions = make([]*model.Question, len(insertedQuestions))
		for i, iq := range insertedQuestions {
			practiceTest.Questions[i] = &model.Question{ID: iq.ID}
		}
	}

	if len(studysetIDs) > 0 {
		placeholders := make([]string, len(studysetIDs))
		args := make([]interface{}, len(studysetIDs)+1)
		args[0] = practiceTest.ID
		for i, studysetID := range studysetIDs {
			placeholders[i] = fmt.Sprintf("($1, $%d)", i+2)
			args[i+1] = studysetID
		}
		sql := fmt.Sprintf("INSERT INTO practice_test_studysets (practice_test_id, studyset_id) VALUES %s", strings.Join(placeholders, ","))
		if _, err := tx.Exec(ctx, sql, args...); err != nil {
			return nil, fmt.Errorf("failed to insert practice test studysets: %w", err)
		}
	}

	if len(termProgressMap) > 0 {
		termProgress := make([]*model.TermProgressInput, 0, len(termProgressMap))
		for _, tp := range termProgressMap {
			termProgress = append(termProgress, tp)
		}

		valueStrings := make([]string, 0, len(termProgress))
		valueArgs := make([]interface{}, 0, len(termProgress)*8)
		termIDs := make([]string, len(termProgress))

		for i, p := range termProgress {
			termIDs[i] = p.TermID
			// Each row has 8 parameters
			base := i*8 + 1
			valueStrings = append(valueStrings, fmt.Sprintf(
				"($%d::uuid,$%d::uuid,$%d::timestamptz,$%d::timestamptz,CASE WHEN $%d IS NOT NULL THEN 1 ELSE 0 END,$%d::timestamptz,$%d::timestamptz,CASE WHEN $%d IS NOT NULL THEN 1 ELSE 0 END,COALESCE($%d::int,0),COALESCE($%d::int,0),COALESCE($%d::int,0),COALESCE($%d::int,0))",
				base, base+1, base+2, base+2, base+2, base+3, base+3, base+3, base+4, base+5, base+6, base+7,
			))

			valueArgs = append(valueArgs,
				p.TermID,
				authedUser.ID,
				p.TermReviewedAt,
				p.DefReviewedAt,
				p.TermCorrectIncrease,
				p.TermIncorrectIncrease,
				p.DefCorrectIncrease,
				p.DefIncorrectIncrease,
			)
		}

		query := fmt.Sprintf(`
			INSERT INTO term_progress (
				term_id, user_id,
				term_first_reviewed_at, term_last_reviewed_at,
				term_review_count,
				def_first_reviewed_at, def_last_reviewed_at,
				def_review_count,
				term_correct_count, term_incorrect_count,
				def_correct_count, def_incorrect_count
			)
			SELECT v.term_id::uuid, v.user_id::uuid,
				v.term_first_reviewed_at::timestamptz, v.term_last_reviewed_at::timestamptz,
				v.term_review_count::int,
				v.def_first_reviewed_at::timestamptz, v.def_last_reviewed_at::timestamptz,
				v.def_review_count::int,
				v.term_correct_count::int, v.term_incorrect_count::int,
				v.def_correct_count::int, v.def_incorrect_count::int
			FROM (VALUES %s) AS v(
				term_id, user_id,
				term_first_reviewed_at, term_last_reviewed_at,
				term_review_count,
				def_first_reviewed_at, def_last_reviewed_at,
				def_review_count,
				term_correct_count, term_incorrect_count,
				def_correct_count, def_incorrect_count
			)
			JOIN terms t ON t.id = v.term_id::uuid
			JOIN studysets s ON s.id = t.studyset_id
			WHERE s.draft = false AND (s.private = false OR s.user_id = v.user_id::uuid)
			ON CONFLICT (term_id, user_id) DO UPDATE SET
				term_last_reviewed_at = COALESCE(EXCLUDED.term_last_reviewed_at, term_progress.term_last_reviewed_at),
				def_last_reviewed_at = COALESCE(EXCLUDED.def_last_reviewed_at, term_progress.def_last_reviewed_at),
				term_review_count = term_progress.term_review_count +
					(CASE WHEN EXCLUDED.term_last_reviewed_at IS NOT NULL THEN 1 ELSE 0 END),
				def_review_count = term_progress.def_review_count +
					(CASE WHEN EXCLUDED.def_last_reviewed_at IS NOT NULL THEN 1 ELSE 0 END),
				term_correct_count = term_progress.term_correct_count + EXCLUDED.term_correct_count,
				term_incorrect_count = term_progress.term_incorrect_count + EXCLUDED.term_incorrect_count,
				def_correct_count = term_progress.def_correct_count + EXCLUDED.def_correct_count,
				def_incorrect_count = term_progress.def_incorrect_count + EXCLUDED.def_incorrect_count
			RETURNING term_progress.id,
				to_char(term_progress.term_first_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as term_first_reviewed_at,
				to_char(term_progress.term_last_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as term_last_reviewed_at,
				term_progress.term_review_count,
				to_char(term_progress.def_first_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as def_first_reviewed_at,
				to_char(term_progress.def_last_reviewed_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as def_last_reviewed_at,
				term_progress.def_review_count,
				term_progress.term_correct_count, term_progress.term_incorrect_count,
				term_progress.def_correct_count, term_progress.def_incorrect_count
		`, strings.Join(valueStrings, ","))

		var results []*model.TermProgress
		if err := pgxscan.Select(ctx, tx, &results, query, valueArgs...); err != nil {
			return nil, fmt.Errorf("bulk upsert of term progress failed: %w", err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return &practiceTest, nil
}

// UpdatePracticeTestQuestion is the resolver for the updatePracticeTestQuestion field.
func (r *mutationResolver) UpdatePracticeTestQuestion(ctx context.Context, id string, correct bool, userMarkedCorrect *bool) (*model.Question, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var row model.QuestionRow
	err = pgxscan.Get(ctx, tx, &row, `
		SELECT q.id, q.practice_test_id, q.term_id, q.term_snapshot, q.def_snapshot, q.type, q.answer_with, q.correct, q.position, q.data
		FROM practice_test_questions q
		JOIN practice_tests pt ON q.practice_test_id = pt.id
		WHERE q.id = $1 AND pt.user_id = $2
	`, id, authedUser.ID)
	if err != nil {
		return nil, fmt.Errorf("question not found or not owned by user: %w", err)
	}

	oldCorrect := row.Correct
	newCorrect := correct

	if row.Type != "FRQ" {
		return nil, fmt.Errorf("only FRQ questions can be updated via this mutation")
	}

	var data map[string]interface{}
	if err := json.Unmarshal(row.Data, &data); err != nil {
		return nil, fmt.Errorf("failed to unmarshal question data: %w", err)
	}

	if userMarkedCorrect != nil {
		data["userMarkedCorrect"] = *userMarkedCorrect
	}

	newDataBytes, err := json.Marshal(data)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal new question data: %w", err)
	}

	_, err = tx.Exec(ctx, `
		UPDATE practice_test_questions
		SET correct = $2, data = $3
		WHERE id = $1
	`, id, newCorrect, newDataBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to update question: %w", err)
	}

	_, err = tx.Exec(ctx, `
		UPDATE review_events
		SET correct = $1
		WHERE practice_test_question_id = $2
	`, newCorrect, id)
	if err != nil {
		return nil, fmt.Errorf("failed to update review events: %w", err)
	}

	if oldCorrect != newCorrect {
		diff := int32(1)
		if oldCorrect {
			diff = -1
		}
		_, err = tx.Exec(ctx, `
			UPDATE practice_tests
			SET questions_correct = questions_correct + $1
			WHERE id = $2
		`, diff, row.PracticeTestID)
		if err != nil {
			return nil, fmt.Errorf("failed to update practice test correct count: %w", err)
		}

		if row.TermID != nil {
			var correctInc, incorrectInc int32
			if newCorrect {
				correctInc = 1
				incorrectInc = -1
			} else {
				correctInc = -1
				incorrectInc = 1
			}

			var termCorrectInc, termIncorrectInc, defCorrectInc, defIncorrectInc int32
			if row.AnswerWith == model.AnswerWithDef {
				defCorrectInc = correctInc
				defIncorrectInc = incorrectInc
			} else {
				termCorrectInc = correctInc
				termIncorrectInc = incorrectInc
			}

			_, err = tx.Exec(ctx, `
				UPDATE term_progress
				SET term_correct_count = term_correct_count + $3,
				    term_incorrect_count = term_incorrect_count + $4,
				    def_correct_count = def_correct_count + $5,
				    def_incorrect_count = def_incorrect_count + $6
				WHERE term_id = $1 AND user_id = $2
			`, *row.TermID, authedUser.ID, termCorrectInc, termIncorrectInc, defCorrectInc, defIncorrectInc)
			if err != nil {
				return nil, fmt.Errorf("failed to update term progress: %w", err)
			}
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	// Reconstruct and return the question
	q := &model.Question{}
	termATP := &model.TermAtp{
		ID:   row.TermID,
		Term: row.Term,
		Def:  row.Def,
	}
	umc := false
	if userMarkedCorrect != nil {
		umc = *userMarkedCorrect
	} else if val, ok := data["userMarkedCorrect"].(bool); ok {
		umc = val
	}

	q.ID = row.ID
	q.Frq = &model.Frq{
		Term:              termATP,
		AnswerWith:        row.AnswerWith,
		Correct:           newCorrect,
		UserMarkedCorrect: &umc,
		AnsweredString:    data["answeredString"].(string),
	}

	return q, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, name string) (*model.Folder, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if len(name) > MaxFolderNameLen {
		name = name[:MaxFolderNameLen]
	}

	sql := `
		INSERT INTO folders (user_id, name)
		VALUES ($1, $2)
		RETURNING id, name
	`
	var newFolder model.Folder
	err := pgxscan.Get(ctx, r.DB, &newFolder, sql, authedUser.ID, name)
	if err != nil {
		return nil, fmt.Errorf("failed to create studyset: %w", err)
	}

	return &newFolder, nil
}

// RenameFolder is the resolver for the renameFolder field.
func (r *mutationResolver) RenameFolder(ctx context.Context, id string, name string) (*model.Folder, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if len(name) > MaxFolderNameLen {
		name = name[:MaxFolderNameLen]
	}

	sql := `
		UPDATE folders SET name = $1
		WHERE user_id = $2 AND id = $3
		RETURNING id, name
	`
	var folder model.Folder
	err := pgxscan.Get(ctx, r.DB, &folder, sql, name, authedUser.ID, id)
	if err != nil {
		return nil, fmt.Errorf("failed to rename folder: %w", err)
	}

	return &folder, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id string) (*string, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	res, err := r.DB.Exec(
		ctx,
		"DELETE FROM folders WHERE id = $1 AND user_id = $2",
		id,
		authedUser.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to delete folder: %w", err)
	}

	if res.RowsAffected() == 0 {
		return nil, fmt.Errorf("folder not found or access denied")
	}

	return &id, nil
}

// SetStudysetFolder is the resolver for the setStudysetFolder field.
func (r *mutationResolver) SetStudysetFolder(ctx context.Context, studysetID string, folderID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	_, err := r.DB.Exec(
		ctx,
		`INSERT INTO folder_studysets (user_id, studyset_id, folder_id)
		SELECT $1, s.id, f.id
		FROM studysets s
		JOIN folders f ON f.id = $3::uuid
		WHERE s.id = $2::uuid
		  AND ((s.draft = false AND s.private = false) OR s.user_id = $1)
		  AND f.user_id = $1
		ON CONFLICT (user_id, studyset_id) DO UPDATE
		SET folder_id = EXCLUDED.folder_id`,
		authedUser.ID,
		studysetID,
		folderID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to add/move studyset to folder: %w", err)
	}

	yay := true
	return &yay, nil
}

// RemoveStudysetFromFolder is the resolver for the removeStudysetFromFolder field.
func (r *mutationResolver) RemoveStudysetFromFolder(ctx context.Context, studysetID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	_, err := r.DB.Exec(
		ctx,
		"DELETE FROM folder_studysets WHERE studyset_id = $1 AND user_id = $2",
		studysetID,
		authedUser.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to unsave studyset: %w", err)
	}

	yay := true
	return &yay, nil
}

// SaveStudyset is the resolver for the saveStudyset field.
func (r *mutationResolver) SaveStudyset(ctx context.Context, studysetID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	res, err := r.DB.Exec(
		ctx,
		`INSERT INTO saved_studysets (user_id, studyset_id)
		SELECT $1, id FROM studysets
		WHERE id = $2 AND (private = false OR user_id = $1) AND draft = false`,
		authedUser.ID,
		studysetID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to save studyset: %w", err)
	}
	if res.RowsAffected() == 0 {
		return nil, fmt.Errorf("studyset not found, private, or is a draft")
	}

	yay := true
	return &yay, nil
}

// UnsaveStudyset is the resolver for the unsaveStudyset field.
func (r *mutationResolver) UnsaveStudyset(ctx context.Context, studysetID string) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	_, err := r.DB.Exec(
		ctx,
		"DELETE FROM saved_studysets WHERE studyset_id = $1 AND user_id = $2",
		studysetID,
		authedUser.ID,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to unsave studyset: %w", err)
	}

	yay := true
	return &yay, nil
}

// SetStudysetSeoIndexing is the resolver for the setStudysetSeoIndexing field.
func (r *mutationResolver) SetStudysetSeoIndexing(ctx context.Context, studysetID string, approved bool) (bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return false, errors.New("not authenticated")
	}
	if authedUser.ModPerms == nil || !*authedUser.ModPerms {
		return false, errors.New("missing moderator permissions needed to set studyset SEO indexing approval")
	}
	tag, err := r.DB.Exec(
		ctx,
		"UPDATE studysets SET seo_indexing_approved = $1 WHERE id = $2",
		approved,
		studysetID,
	)
	if err != nil {
		log.Error().Err(err).Msg("DB Error in SetStudysetSeoIndexing")
		return false, errors.New("DB Error in SetStudysetSeoIndexing")
	}
	return tag.RowsAffected() == 1, nil
}

// UpdateFsrsCard is the resolver for the updateFsrsCard field.
func (r *mutationResolver) UpdateFsrsCard(ctx context.Context, termID string, card model.FSRSCardInput) (bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil {
		return false, errors.New("not authenticated")
	}

	tag, err := r.DB.Exec(
		ctx,
		`INSERT INTO fsrs_cards (term_id,
    user_id,
    difficulty,
    due,
    lapses,
    last_review,
    learning_steps,
    reps,
    scheduled_days,
    stability,
    state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (term_id, user_id)
DO UPDATE SET
    term_id = EXCLUDED.term_id,
    user_id = EXCLUDED.user_id,
    difficulty = EXCLUDED.difficulty,
    due = EXCLUDED.due,
    lapses = EXCLUDED.lapses,
    last_review = EXCLUDED.last_review,
    learning_steps = EXCLUDED.learning_steps,
    reps = EXCLUDED.reps,
    scheduled_days = EXCLUDED.scheduled_days,
    stability = EXCLUDED.stability,
    state = EXCLUDED.state`,
		termID,
		authedUser.ID,
		card.Difficulty,
		card.Due,
		card.Lapses,
		card.LastReview,
		card.LearningSteps,
		card.Reps,
		card.ScheduledDays,
		card.Stability,
		card.State,
	)
	if err != nil {
		log.Error().Err(err).Msg("DB Error in UpdateFsrsCard")
		return false, errors.New("DB Error in UpdateFsrsCard")
	}
	return tag.RowsAffected() == 1, nil
}

// RecordFsrsReviewLog is the resolver for the recordFsrsReviewLog field.
func (r *mutationResolver) RecordFsrsReviewLog(ctx context.Context, termID string, reviewLog model.FSRSReviewLogInput) (bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil {
		return false, errors.New("not authenticated")
	}

	tag, err := r.DB.Exec(
		ctx,
		`INSERT INTO fsrs_review_logs (
    term_id,
    user_id,
    difficulty,
    due,
    learning_steps,
    rating,
    review,
    scheduled_days,
    stability,
    state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
		termID,
		authedUser.ID,
		reviewLog.Difficulty,
		reviewLog.Due,
		reviewLog.LearningSteps,
		reviewLog.Rating,
		reviewLog.Review,
		reviewLog.ScheduledDays,
		reviewLog.Stability,
		reviewLog.State,
	)
	if err != nil {
		log.Error().Err(err).Msg("DB Error in RecordFsrsReviewLog")
		return false, errors.New("DB Error in RecordFsrsReviewLog")
	}
	return tag.RowsAffected() == 1, nil
}

// RecordMatchActivity is the resolver for the recordMatchActivity field.
func (r *mutationResolver) RecordMatchActivity(ctx context.Context, input model.MatchActivityInput) (*model.MatchActivity, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	tx, err := r.DB.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	var matchActivityID string
	err = tx.QueryRow(ctx, `
		INSERT INTO public.match_activities (user_id, duration_ms)
		VALUES ($1, $2)
		RETURNING id
	`, authedUser.ID, input.DurationMs).Scan(&matchActivityID)
	if err != nil {
		return nil, fmt.Errorf("failed to insert match activity: %w", err)
	}

	if len(input.TermIds) > 0 {
		var studysetIDs []string
		err = pgxscan.Select(ctx, tx, &studysetIDs, `
			SELECT DISTINCT studyset_id FROM terms WHERE id = ANY($1)
		`, input.TermIds)
		if err != nil {
			return nil, fmt.Errorf("failed to query studysets for terms: %w", err)
		}

		if len(studysetIDs) > 0 {
			mssPlaceholders := make([]string, len(studysetIDs))
			mssArgs := make([]interface{}, len(studysetIDs)+1)
			mssArgs[0] = matchActivityID
			for i, sid := range studysetIDs {
				mssPlaceholders[i] = fmt.Sprintf("($1, $%d)", i+2)
				mssArgs[i+1] = sid
			}
			_, err = tx.Exec(ctx, fmt.Sprintf(`
				INSERT INTO match_activity_studysets (match_id, studyset_id)
				VALUES %s ON CONFLICT DO NOTHING
			`, strings.Join(mssPlaceholders, ",")), mssArgs...)
			if err != nil {
				return nil, fmt.Errorf("failed to insert match activity studysets: %w", err)
			}
		}
	}

	var errs []string
	idx := 0
	var placeholders []string
	args := []interface{}{authedUser.ID, matchActivityID, model.ReviewActivityTypeMatch}

	for _, termID := range input.TermIds {
		base := idx*2 + 4
		placeholders = append(placeholders, fmt.Sprintf("($1, $%d, true, NULL, $%d, $3, $2)", base, base+1))
		args = append(args, termID, termID)
		idx++
	}

	for _, pair := range input.IncorrectPairIds {
		if len(pair) < 2 {
			errs = append(errs, "invalid incorrect pair: expected at least 2 elements")
			continue
		}
		base := idx*2 + 4
		placeholders = append(placeholders, fmt.Sprintf("($1, $%d, false, NULL, $%d, $3, $2)", base, base+1))
		args = append(args, pair[0], pair[1])
		idx++
	}

	if len(placeholders) > 0 {
		sql := fmt.Sprintf(`INSERT INTO review_events (
			user_id, term_id, correct, answer_with, answered_term_id, review_activity_type, match_activity_id
		) VALUES %s`, strings.Join(placeholders, ","))

		if _, err := tx.Exec(ctx, sql, args...); err != nil {
			return nil, fmt.Errorf("failed to insert review events: %w", err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	result := &model.MatchActivity{
		DurationMs:       input.DurationMs,
		EndTimestamp:     time.Now().UTC().Format(time.RFC3339Nano),
		TermIds:          input.TermIds,
		IncorrectPairIds: input.IncorrectPairIds,
	}

	if len(errs) > 0 {
		return result, fmt.Errorf(strings.Join(errs, "; "))
	}

	return result, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
