package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"quizfreely/api/auth"
	"quizfreely/api/graph"
	"quizfreely/api/graph/loader"
	"quizfreely/api/graph/model"

	"github.com/georgysavva/scany/v2/pgxscan"
)

// Subject is the resolver for the subject field.
func (r *studysetResolver) Subject(ctx context.Context, obj *model.Studyset) (*model.Subject, error) {
	if obj.SubjectID == nil {
		return nil, nil
	}

	var subject model.Subject
	err := pgxscan.Get(
		ctx,
		r.DB,
		&subject,
		`SELECT id, name, category FROM subjects WHERE id = $1`,
		*obj.SubjectID,
	)
	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to get subject from studyset: %w", err)
	}

	return &subject, nil
}

// User is the resolver for the user field.
func (r *studysetResolver) User(ctx context.Context, obj *model.Studyset) (*model.User, error) {
	if obj.UserID == nil {
		return nil, nil
	}

	return loader.GetUser(ctx, *obj.UserID)
}

// Terms is the resolver for the terms field.
func (r *studysetResolver) Terms(ctx context.Context, obj *model.Studyset) ([]*model.Term, error) {
	if obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermsByStudysetID(ctx, *obj.ID)
}

// TermsCount is the resolver for the terms_count field.
func (r *studysetResolver) TermsCount(ctx context.Context, obj *model.Studyset) (*int32, error) {
	if obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermsCountByStudysetID(ctx, *obj.ID)
}

// PracticeTests is the resolver for the practice_tests field.
func (r *studysetResolver) PracticeTests(ctx context.Context, obj *model.Studyset) ([]*model.PracticeTest, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetPracticeTestsByStudysetID(ctx, *obj.ID)
}

// Saved is the resolver for the saved field.
func (r *studysetResolver) Saved(ctx context.Context, obj *model.Studyset) (*bool, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if obj == nil || obj.ID == nil {
		return nil, nil
	}

	var result bool
	sql := `SELECT EXISTS (
		SELECT 1 FROM saved_studysets WHERE studyset_id = $1 AND user_id = $2
	)`
	err := pgxscan.Get(ctx, r.DB, &result, sql, *obj.ID, authedUser.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to check studyset saved field: %w", err)
	}

	return &result, nil
}

// Folder is the resolver for the folder field.
func (r *studysetResolver) Folder(ctx context.Context, obj *model.Studyset) (*model.Folder, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	if obj == nil || obj.ID == nil {
		return nil, nil
	}

	var folder model.Folder
	sql := `
		SELECT f.id, f.name FROM folders f
	    JOIN folder_studysets fs ON fs.folder_id = f.id
	    WHERE fs.studyset_id = $1 AND fs.user_id = $2 AND f.user_id = $2
	`
	err := pgxscan.Get(ctx, r.DB, &folder, sql, *obj.ID, authedUser.ID)
	if err != nil {
		if pgxscan.NotFound(err) {
			return nil, nil
		}

		return nil, fmt.Errorf("failed to check studyset folder field: %w", err)
	}

	return &folder, nil
}

// Studyset returns graph.StudysetResolver implementation.
func (r *Resolver) Studyset() graph.StudysetResolver { return &studysetResolver{r} }

type studysetResolver struct{ *Resolver }
