package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"quizfreely/api/graph"
	"quizfreely/api/graph/cursor"
	"quizfreely/api/graph/model"

	"github.com/georgysavva/scany/v2/pgxscan"
)

// Studysets is the resolver for the studysets field.
func (r *subjectResolver) Studysets(ctx context.Context, obj *model.Subject, first *int32, after *string, last *int32, before *string) (*model.StudysetConnection, error) {
	if obj == nil || obj.ID == nil {
		return nil, nil
	}

	l := 24
	if first != nil && *first > 0 && *first < 1000 {
		l = int(*first)
	} else if last != nil && *last > 0 && *last < 1000 {
		l = int(*last)
	}
	limit := l + 1

	cursorTS, cursorID := cursor.DecodeStudysetCursor(ptrToString(after))
	beforeCursorTS, beforeCursorID := cursor.DecodeStudysetCursor(ptrToString(before))

	isBackward := beforeCursorID != ""
	hasPrevious := false
	if !isBackward {
		hasPrevious = cursorTS != "" || cursorID != ""
	}

	var studysets []*model.Studyset
	var err error
	if isBackward {
		sql := `
			SELECT
				s.id,
				s.user_id,
				s.title,
				s.draft,
				s.private,
				s.subject_id,
				s.seo_indexing_approved,
				to_char(s.created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
				to_char(s.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
			FROM studysets s
			JOIN subjects ON s.subject_id = subjects.id
			WHERE subjects.id = $1
				AND s.private = false AND s.draft = false
				AND (to_char(s.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM'), s.id) > ($2, $3::uuid)
			ORDER BY s.updated_at ASC, s.id ASC
			LIMIT $4
		`
		err = pgxscan.Select(ctx, r.DB, &studysets, sql, obj.ID, beforeCursorTS, beforeCursorID, limit)
		if err == nil {
			hasPrevious = len(studysets) > l
			if hasPrevious {
				studysets = studysets[:l]
			}
			// Reverse
			for i, j := 0, len(studysets)-1; i < j; i, j = i+1, j-1 {
				studysets[i], studysets[j] = studysets[j], studysets[i]
			}
		}
	} else if cursorID != "" {
		sql := `
			SELECT
				s.id,
				s.user_id,
				s.title,
				s.draft,
				s.private,
				s.subject_id,
				s.seo_indexing_approved,
				to_char(s.created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
				to_char(s.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
			FROM studysets s
			JOIN subjects ON s.subject_id = subjects.id
			WHERE subjects.id = $1
				AND s.private = false AND s.draft = false
				AND (to_char(s.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM'), s.id) < ($2, $3::uuid)
			ORDER BY s.updated_at DESC, s.id DESC
			LIMIT $4
		`
		err = pgxscan.Select(ctx, r.DB, &studysets, sql, obj.ID, cursorTS, cursorID, limit)
	} else {
		sql := `
			SELECT
				s.id,
				s.user_id,
				s.title,
				s.draft,
				s.private,
				s.subject_id,
				s.seo_indexing_approved,
				to_char(s.created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as created_at,
				to_char(s.updated_at, 'YYYY-MM-DD"T"HH24:MI:SS.MSTZH:TZM') as updated_at
			FROM studysets s
			JOIN subjects ON s.subject_id = subjects.id
			WHERE subjects.id = $1
				AND s.private = false AND s.draft = false
			ORDER BY s.updated_at DESC, s.id DESC
			LIMIT $2
		`
		err = pgxscan.Select(ctx, r.DB, &studysets, sql, obj.ID, limit)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to fetch subject's studysets: %w", err)
	}

	hasNext := false
	if isBackward {
		hasNext = true
	} else {
		hasNext = len(studysets) > l
		if hasNext {
			studysets = studysets[:l]
		}
	}
	getCursor := func(s *model.Studyset) (string, string) {
		return ptrToString(s.UpdatedAt), ptrToString(s.ID)
	}
	return cursor.StudysetConnectionFrom(studysets, hasNext, hasPrevious, getCursor), nil
}

// StudysetCount is the resolver for the studysetCount field.
func (r *subjectResolver) StudysetCount(ctx context.Context, obj *model.Subject) (int32, error) {
	if obj == nil || obj.ID == nil {
		return 0, nil
	}

	// Always count public studysets only for subjects?
	// The `Studysets` resolver filters `private = false`.
	// So we should do the same here.

	var count int32
	err := r.DB.QueryRow(ctx, "SELECT count(*) FROM studysets WHERE subject_id = $1 AND private = false AND draft = false", obj.ID).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("failed to count subject studysets: %w", err)
	}

	return count, nil
}

// Subject returns graph.SubjectResolver implementation.
func (r *Resolver) Subject() graph.SubjectResolver { return &subjectResolver{r} }

type subjectResolver struct{ *Resolver }
