package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"quizfreely/api/auth"
	"quizfreely/api/graph"
	"quizfreely/api/graph/loader"
	"quizfreely/api/graph/model"
)

// Progress is the resolver for the progress field.
func (r *termResolver) Progress(ctx context.Context, obj *model.Term) (*model.TermProgress, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermProgress(ctx, *obj.ID)
}

// FsrsCard is the resolver for the fsrsCard field.
func (r *termResolver) FsrsCard(ctx context.Context, obj *model.Term) (*model.FSRSCard, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetFSRSCardByTermID(ctx, *obj.ID)
}

// FsrsReviewLogs is the resolver for the fsrsReviewLogs field.
func (r *termResolver) FsrsReviewLogs(ctx context.Context, obj *model.Term) ([]*model.FSRSReviewLog, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetFSRSReviewLogsByTermID(ctx, *obj.ID)
}

// PracticeTests is the resolver for the practiceTests field.
func (r *termResolver) PracticeTests(ctx context.Context, obj *model.Term) ([]*model.PracticeTest, error) {
	if obj.ID == nil {
		return []*model.PracticeTest{}, nil
	}

	return loader.GetPracticeTestsByTermID(ctx, *obj.ID)
}

// Term returns graph.TermResolver implementation.
func (r *Resolver) Term() graph.TermResolver { return &termResolver{r} }

type termResolver struct{ *Resolver }
