package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"quizfreely/api/auth"
	"quizfreely/api/graph"
	"quizfreely/api/graph/loader"
	"quizfreely/api/graph/model"
)

// Progress is the resolver for the progress field.
func (r *termResolver) Progress(ctx context.Context, obj *model.Term) (*model.TermProgress, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermProgress(ctx, *obj.ID)
}

// ProgressHistory is the resolver for the progressHistory field.
func (r *termResolver) ProgressHistory(ctx context.Context, obj *model.Term) ([]*model.TermProgressHistory, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermProgressHistory(ctx, *obj.ID)
}

// TopConfusionPairs is the resolver for the top_confusion_pairs field.
func (r *termResolver) TopConfusionPairs(ctx context.Context, obj *model.Term) ([]*model.TermConfusionPair, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermTopConfusionPairs(ctx, *obj.ID)
}

// TopReverseConfusionPairs is the resolver for the top_reverse_confusion_pairs field.
func (r *termResolver) TopReverseConfusionPairs(ctx context.Context, obj *model.Term) ([]*model.TermConfusionPair, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetTermTopReverseConfusionPairs(ctx, *obj.ID)
}

// Term is the resolver for the term field.
func (r *termConfusionPairResolver) Term(ctx context.Context, obj *model.TermConfusionPair) (*model.Term, error) {
	if obj.TermID == nil {
		return nil, nil
	}

	return loader.GetTermByID(ctx, *obj.TermID)
}

// ConfusedTerm is the resolver for the confusedTerm field.
func (r *termConfusionPairResolver) ConfusedTerm(ctx context.Context, obj *model.TermConfusionPair) (*model.Term, error) {
	if obj.ConfusedTermID == nil {
		return nil, nil
	}

	return loader.GetTermByID(ctx, *obj.ConfusedTermID)
}

// Term returns graph.TermResolver implementation.
func (r *Resolver) Term() graph.TermResolver { return &termResolver{r} }

// TermConfusionPair returns graph.TermConfusionPairResolver implementation.
func (r *Resolver) TermConfusionPair() graph.TermConfusionPairResolver {
	return &termConfusionPairResolver{r}
}

type termResolver struct{ *Resolver }
type termConfusionPairResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *termResolver) FsrsCard(ctx context.Context, obj *model.Term) (*model.FSRSCard, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetFSRSCardByTermID(ctx, *obj.ID)
}
func (r *termResolver) FsrsReviewLogs(ctx context.Context, obj *model.Term) ([]*model.FSRSReviewLog, error) {
	authedUser := auth.AuthedUserContext(ctx)
	if authedUser == nil || authedUser.ID == nil || obj.ID == nil {
		return nil, nil
	}

	return loader.GetFSRSReviewLogsByTermID(ctx, *obj.ID)
}
*/
