name: Push to GitHub
on:
  workflow_dispatch:
jobs:
  push_to_gh:
    name: Push to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Clone from Codeberg
        run: git clone https://codeberg.org/quizfreely/api.git
      - name: Push to GitHub
        run: |
          cd api
          git push https://ehanahamed:${{ secrets.GH_TOKEN }}@github.com/quizfreely/api.git --all
